export interface StateComparisonData {
  stateCode: string;
  stateName: string;
  taxRate: number;
  costOfLivingIndex: number;
  avgPhysicianSalary: number;
  malpracticeEnvironment: "favorable" | "moderate" | "challenging";
  majorAirports: string[];
  climate: string;
}

export const STATE_COMPARISON_DATA: Record<string, StateComparisonData> = {
  AL: {
    stateCode: "AL",
    stateName: "Alabama",
    taxRate: 5.0,
    costOfLivingIndex: 88,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["BHM", "HSV", "MOB"],
    climate: "Subtropical, hot humid summers, mild winters",
  },
  AK: {
    stateCode: "AK",
    stateName: "Alaska",
    taxRate: 0,
    costOfLivingIndex: 127,
    avgPhysicianSalary: 370000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["ANC", "FAI"],
    climate: "Subarctic to arctic, long cold winters, cool summers",
  },
  AZ: {
    stateCode: "AZ",
    stateName: "Arizona",
    taxRate: 2.5,
    costOfLivingIndex: 102,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["PHX", "TUS"],
    climate: "Arid desert, very hot summers, mild winters",
  },
  AR: {
    stateCode: "AR",
    stateName: "Arkansas",
    taxRate: 4.4,
    costOfLivingIndex: 87,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["LIT", "XNA"],
    climate: "Humid subtropical, hot summers, mild winters",
  },
  CA: {
    stateCode: "CA",
    stateName: "California",
    taxRate: 13.3,
    costOfLivingIndex: 142,
    avgPhysicianSalary: 360000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["LAX", "SFO", "SAN", "SJC", "OAK"],
    climate: "Mediterranean coast, desert inland, variable by region",
  },
  CO: {
    stateCode: "CO",
    stateName: "Colorado",
    taxRate: 4.4,
    costOfLivingIndex: 105,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["DEN", "COS"],
    climate: "Semi-arid, cold winters, warm summers, high altitude",
  },
  CT: {
    stateCode: "CT",
    stateName: "Connecticut",
    taxRate: 6.99,
    costOfLivingIndex: 121,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["BDL"],
    climate: "Continental, cold winters, warm humid summers",
  },
  DE: {
    stateCode: "DE",
    stateName: "Delaware",
    taxRate: 6.6,
    costOfLivingIndex: 103,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["PHL"],
    climate: "Humid subtropical, mild winters, hot summers",
  },
  FL: {
    stateCode: "FL",
    stateName: "Florida",
    taxRate: 0,
    costOfLivingIndex: 103,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["MIA", "FLL", "TPA", "MCO", "JAX"],
    climate: "Tropical south, subtropical north, hot humid summers",
  },
  GA: {
    stateCode: "GA",
    stateName: "Georgia",
    taxRate: 5.49,
    costOfLivingIndex: 93,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["ATL", "SAV"],
    climate: "Humid subtropical, hot summers, mild winters",
  },
  HI: {
    stateCode: "HI",
    stateName: "Hawaii",
    taxRate: 11.0,
    costOfLivingIndex: 192,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["HNL", "OGG"],
    climate: "Tropical, warm year-round, trade winds",
  },
  ID: {
    stateCode: "ID",
    stateName: "Idaho",
    taxRate: 5.8,
    costOfLivingIndex: 97,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["BOI"],
    climate: "Semi-arid, cold winters, warm dry summers",
  },
  IL: {
    stateCode: "IL",
    stateName: "Illinois",
    taxRate: 4.95,
    costOfLivingIndex: 96,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["ORD", "MDW"],
    climate: "Continental, cold winters, hot humid summers",
  },
  IN: {
    stateCode: "IN",
    stateName: "Indiana",
    taxRate: 3.05,
    costOfLivingIndex: 90,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["IND"],
    climate: "Continental, cold winters, warm humid summers",
  },
  IA: {
    stateCode: "IA",
    stateName: "Iowa",
    taxRate: 3.8,
    costOfLivingIndex: 89,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["DSM", "CID"],
    climate: "Continental, cold winters, hot humid summers",
  },
  KS: {
    stateCode: "KS",
    stateName: "Kansas",
    taxRate: 5.7,
    costOfLivingIndex: 89,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["MCI", "ICT"],
    climate: "Continental, cold winters, hot summers, tornado-prone",
  },
  KY: {
    stateCode: "KY",
    stateName: "Kentucky",
    taxRate: 4.0,
    costOfLivingIndex: 90,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["SDF", "CVG"],
    climate: "Humid subtropical, mild winters, hot summers",
  },
  LA: {
    stateCode: "LA",
    stateName: "Louisiana",
    taxRate: 4.25,
    costOfLivingIndex: 91,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["MSY", "BTR"],
    climate: "Subtropical, hot humid summers, mild winters, hurricane risk",
  },
  ME: {
    stateCode: "ME",
    stateName: "Maine",
    taxRate: 7.15,
    costOfLivingIndex: 113,
    avgPhysicianSalary: 300000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["PWM"],
    climate: "Continental, cold winters, cool summers",
  },
  MD: {
    stateCode: "MD",
    stateName: "Maryland",
    taxRate: 5.75,
    costOfLivingIndex: 116,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["BWI"],
    climate: "Humid subtropical, mild winters, hot humid summers",
  },
  MA: {
    stateCode: "MA",
    stateName: "Massachusetts",
    taxRate: 5.0,
    costOfLivingIndex: 135,
    avgPhysicianSalary: 350000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["BOS"],
    climate: "Continental, cold winters, warm humid summers",
  },
  MI: {
    stateCode: "MI",
    stateName: "Michigan",
    taxRate: 4.25,
    costOfLivingIndex: 93,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["DTW", "GRR"],
    climate: "Continental, cold snowy winters, warm summers",
  },
  MN: {
    stateCode: "MN",
    stateName: "Minnesota",
    taxRate: 9.85,
    costOfLivingIndex: 98,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["MSP"],
    climate: "Continental, very cold winters, warm humid summers",
  },
  MS: {
    stateCode: "MS",
    stateName: "Mississippi",
    taxRate: 5.0,
    costOfLivingIndex: 84,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["JAN"],
    climate: "Subtropical, hot humid summers, mild winters",
  },
  MO: {
    stateCode: "MO",
    stateName: "Missouri",
    taxRate: 4.95,
    costOfLivingIndex: 89,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["STL", "MCI"],
    climate: "Continental, cold winters, hot humid summers",
  },
  MT: {
    stateCode: "MT",
    stateName: "Montana",
    taxRate: 5.9,
    costOfLivingIndex: 100,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["BZN", "BIL"],
    climate: "Continental, cold winters, warm dry summers",
  },
  NE: {
    stateCode: "NE",
    stateName: "Nebraska",
    taxRate: 5.84,
    costOfLivingIndex: 91,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["OMA"],
    climate: "Continental, cold winters, hot summers, tornado-prone",
  },
  NV: {
    stateCode: "NV",
    stateName: "Nevada",
    taxRate: 0,
    costOfLivingIndex: 104,
    avgPhysicianSalary: 340000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["LAS", "RNO"],
    climate: "Arid desert, hot summers, mild winters",
  },
  NH: {
    stateCode: "NH",
    stateName: "New Hampshire",
    taxRate: 0,
    costOfLivingIndex: 115,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["MHT"],
    climate: "Continental, cold winters, warm summers",
  },
  NJ: {
    stateCode: "NJ",
    stateName: "New Jersey",
    taxRate: 10.75,
    costOfLivingIndex: 120,
    avgPhysicianSalary: 350000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["EWR"],
    climate: "Continental, cold winters, hot humid summers",
  },
  NM: {
    stateCode: "NM",
    stateName: "New Mexico",
    taxRate: 5.9,
    costOfLivingIndex: 93,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["ABQ"],
    climate: "Arid, hot summers, mild winters, high desert",
  },
  NY: {
    stateCode: "NY",
    stateName: "New York",
    taxRate: 10.9,
    costOfLivingIndex: 140,
    avgPhysicianSalary: 370000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["JFK", "LGA", "EWR", "BUF"],
    climate: "Continental, cold winters, hot summers, variable by region",
  },
  NC: {
    stateCode: "NC",
    stateName: "North Carolina",
    taxRate: 4.5,
    costOfLivingIndex: 96,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["CLT", "RDU"],
    climate: "Humid subtropical, mild winters, hot summers",
  },
  ND: {
    stateCode: "ND",
    stateName: "North Dakota",
    taxRate: 1.95,
    costOfLivingIndex: 93,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["FAR", "BIS"],
    climate: "Continental, very cold winters, warm summers",
  },
  OH: {
    stateCode: "OH",
    stateName: "Ohio",
    taxRate: 3.5,
    costOfLivingIndex: 90,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["CLE", "CMH", "CVG"],
    climate: "Continental, cold winters, warm humid summers",
  },
  OK: {
    stateCode: "OK",
    stateName: "Oklahoma",
    taxRate: 4.75,
    costOfLivingIndex: 87,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["OKC", "TUL"],
    climate: "Subtropical/continental, hot summers, mild winters, tornado-prone",
  },
  OR: {
    stateCode: "OR",
    stateName: "Oregon",
    taxRate: 9.9,
    costOfLivingIndex: 113,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["PDX"],
    climate: "Marine west coast, rainy winters, dry summers",
  },
  PA: {
    stateCode: "PA",
    stateName: "Pennsylvania",
    taxRate: 3.07,
    costOfLivingIndex: 97,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["PHL", "PIT"],
    climate: "Continental, cold winters, warm humid summers",
  },
  RI: {
    stateCode: "RI",
    stateName: "Rhode Island",
    taxRate: 5.99,
    costOfLivingIndex: 113,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["PVD"],
    climate: "Continental, cold winters, warm summers, coastal",
  },
  SC: {
    stateCode: "SC",
    stateName: "South Carolina",
    taxRate: 6.4,
    costOfLivingIndex: 92,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["CHS", "CAE"],
    climate: "Subtropical, hot humid summers, mild winters",
  },
  SD: {
    stateCode: "SD",
    stateName: "South Dakota",
    taxRate: 0,
    costOfLivingIndex: 92,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["FSD", "RAP"],
    climate: "Continental, cold winters, warm summers",
  },
  TN: {
    stateCode: "TN",
    stateName: "Tennessee",
    taxRate: 0,
    costOfLivingIndex: 91,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["BNA", "MEM"],
    climate: "Subtropical, mild winters, hot humid summers",
  },
  TX: {
    stateCode: "TX",
    stateName: "Texas",
    taxRate: 0,
    costOfLivingIndex: 93,
    avgPhysicianSalary: 350000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["DFW", "IAH", "AUS", "SAT", "HOU"],
    climate: "Variable: arid west, humid east, hot summers statewide",
  },
  UT: {
    stateCode: "UT",
    stateName: "Utah",
    taxRate: 4.65,
    costOfLivingIndex: 101,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["SLC"],
    climate: "Semi-arid, cold winters, hot dry summers",
  },
  VT: {
    stateCode: "VT",
    stateName: "Vermont",
    taxRate: 8.75,
    costOfLivingIndex: 115,
    avgPhysicianSalary: 300000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["BTV"],
    climate: "Continental, cold snowy winters, warm summers",
  },
  VA: {
    stateCode: "VA",
    stateName: "Virginia",
    taxRate: 5.75,
    costOfLivingIndex: 103,
    avgPhysicianSalary: 330000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["IAD", "DCA", "RIC"],
    climate: "Humid subtropical, mild winters, hot summers",
  },
  WA: {
    stateCode: "WA",
    stateName: "Washington",
    taxRate: 0,
    costOfLivingIndex: 110,
    avgPhysicianSalary: 350000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["SEA"],
    climate: "Marine west coast, rainy winters, dry mild summers",
  },
  WV: {
    stateCode: "WV",
    stateName: "West Virginia",
    taxRate: 5.12,
    costOfLivingIndex: 84,
    avgPhysicianSalary: 300000,
    malpracticeEnvironment: "challenging",
    majorAirports: ["CRW"],
    climate: "Humid continental, cold winters, warm summers",
  },
  WI: {
    stateCode: "WI",
    stateName: "Wisconsin",
    taxRate: 7.65,
    costOfLivingIndex: 95,
    avgPhysicianSalary: 320000,
    malpracticeEnvironment: "moderate",
    majorAirports: ["MKE", "MSN"],
    climate: "Continental, cold snowy winters, warm summers",
  },
  WY: {
    stateCode: "WY",
    stateName: "Wyoming",
    taxRate: 0,
    costOfLivingIndex: 96,
    avgPhysicianSalary: 310000,
    malpracticeEnvironment: "favorable",
    majorAirports: ["JAC"],
    climate: "Semi-arid, cold winters, warm dry summers, high altitude",
  },
};
