export interface WaiverState {
  stateCode: string;
  stateName: string;
  conradSlots: number;
  flexSlots: number;
  timeline: string;
  processingTime: string;
  priorityAreas: string[];
  specialtyNeeds: string[];
  requirements: string;
  tips: string;
  websiteUrl: string;
}

export const WAIVER_STATES: Record<string, WaiverState> = {
  AL: {
    stateCode: "AL",
    stateName: "Alabama",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a federally designated HPSA or MUA for 3 years. Alabama Department of Public Health sponsors J-1 waiver applications through the Conrad 30 program.",
    tips: "Alabama has strong demand in rural counties. Applications through the Alabama Department of Public Health are typically processed within 60-90 days. Apply early in the federal fiscal year (October).",
    websiteUrl: "https://www.alabamapublichealth.gov",
  },
  AK: {
    stateCode: "AK",
    stateName: "Alaska",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must serve in a designated HPSA or MUA. Alaska Department of Health sponsors Conrad 30 applications. Tribal health facilities are common placement sites.",
    tips: "Alaska has unique opportunities in tribal and native health facilities. Remote locations may offer higher compensation. Contact the Alaska State Medical Association for guidance.",
    websiteUrl: "https://health.alaska.gov",
  },
  AZ: {
    stateCode: "AZ",
    stateName: "Arizona",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-9 months",
    processingTime: "45-90 days",
    priorityAreas: ["Primary Care", "Behavioral Health", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for a minimum of 3 years. Arizona Department of Health Services administers the Conrad 30 program. Preference given to primary care and behavioral health.",
    tips: "Arizona has been expanding its waiver program. Strong demand in Maricopa County suburbs and rural areas. Behavioral health specialists are especially needed. Apply through ADHS early.",
    websiteUrl: "https://www.azdhs.gov",
  },
  AR: {
    stateCode: "AR",
    stateName: "Arkansas",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must practice in a federally designated HPSA or MUA for 3 years. Arkansas Department of Health reviews and sponsors applications.",
    tips: "Arkansas has significant rural health needs. Delta region communities offer strong opportunities. The state is generally IMG-friendly with reasonable processing times.",
    websiteUrl: "https://www.healthy.arkansas.gov",
  },
  CA: {
    stateCode: "CA",
    stateName: "California",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-18 months",
    processingTime: "90-180 days",
    priorityAreas: ["Primary Care", "HPSA Focus", "Community Health Centers"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. California Department of Health Care Access and Information (HCAI) administers the program. Strong preference for FQHC placements.",
    tips: "California is highly competitive due to large applicant pool. FQHC and community health center placements have the best approval rates. Central Valley and rural Northern California have highest need. Apply as early as possible in the fiscal year.",
    websiteUrl: "https://hcai.ca.gov",
  },
  CO: {
    stateCode: "CO",
    stateName: "Colorado",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine"],
    requirements:
      "Must serve in a designated HPSA or MUA. Colorado Department of Public Health and Environment sponsors applications. 3-year service commitment required.",
    tips: "Colorado has growing demand especially on the Eastern Plains and Western Slope. Behavioral health specialists are in particularly high demand. Denver metro HPSA sites are competitive.",
    websiteUrl: "https://cdphe.colorado.gov",
  },
  CT: {
    stateCode: "CT",
    stateName: "Connecticut",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Community Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a designated HPSA or MUA for 3 years. Connecticut Department of Public Health administers the program.",
    tips: "Connecticut has urban underserved areas in Hartford, Bridgeport, and New Haven with strong need. Community health centers are common placement sites.",
    websiteUrl: "https://portal.ct.gov/dph",
  },
  DE: {
    stateCode: "DE",
    stateName: "Delaware",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Delaware Division of Public Health sponsors Conrad 30 applications.",
    tips: "Delaware is a small state with limited slots used each year. Southern Delaware (Sussex County) has the greatest need. Less competitive than neighboring states.",
    websiteUrl: "https://dhss.delaware.gov/dph",
  },
  FL: {
    stateCode: "FL",
    stateName: "Florida",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-15 months",
    processingTime: "90-120 days",
    priorityAreas: ["Primary Care", "Rural Health", "HPSA"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a federally designated HPSA or MUA for 3 years. Florida Department of Health administers the Conrad 30 program. Competitive due to high demand.",
    tips: "Florida is highly competitive. Rural counties in the panhandle and central Florida have better chances. FQHCs and community health centers are preferred. Apply early — slots fill quickly.",
    websiteUrl: "https://www.floridahealth.gov",
  },
  GA: {
    stateCode: "GA",
    stateName: "Georgia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Georgia Department of Community Health sponsors Conrad 30 applications.",
    tips: "Georgia has significant rural health needs, especially in southern and eastern regions. Atlanta metro has some HPSA-designated sites. The state has been increasingly IMG-friendly.",
    websiteUrl: "https://dch.georgia.gov",
  },
  HI: {
    stateCode: "HI",
    stateName: "Hawaii",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Islands", "Native Hawaiian Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Hawaii Department of Health sponsors applications. Neighbor islands have greatest need.",
    tips: "Hawaii has unique opportunities on neighbor islands (Big Island, Maui, Kauai, Molokai). Cost of living is high but some employers provide housing assistance. Limited number of applications each year.",
    websiteUrl: "https://health.hawaii.gov",
  },
  ID: {
    stateCode: "ID",
    stateName: "Idaho",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Idaho Department of Health and Welfare sponsors applications.",
    tips: "Idaho has strong rural health needs throughout the state. Boise metro is more competitive. Eastern and central Idaho have the greatest need. Generally IMG-friendly.",
    websiteUrl: "https://healthandwelfare.idaho.gov",
  },
  IL: {
    stateCode: "IL",
    stateName: "Illinois",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Urban Underserved"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Illinois Department of Public Health administers the Conrad 30 program.",
    tips: "Illinois has opportunities in both rural downstate areas and urban underserved communities in Chicago. FQHCs in Chicago have strong track records. Downstate rural sites are less competitive.",
    websiteUrl: "https://dph.illinois.gov",
  },
  IN: {
    stateCode: "IN",
    stateName: "Indiana",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Indiana State Department of Health administers the program.",
    tips: "Indiana is IMG-friendly with strong rural health needs. Southern Indiana and rural counties have highest demand. Community health centers are common placements. Reasonable processing times.",
    websiteUrl: "https://www.in.gov/health",
  },
  IA: {
    stateCode: "IA",
    stateName: "Iowa",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Iowa Department of Public Health sponsors Conrad 30 applications.",
    tips: "Iowa has widespread rural health needs. Most counties outside Des Moines metro qualify. The state is generally welcoming to IMGs. Community hospitals and FQHCs are common placements.",
    websiteUrl: "https://hhs.iowa.gov",
  },
  KS: {
    stateCode: "KS",
    stateName: "Kansas",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Kansas Department of Health and Environment administers the program.",
    tips: "Kansas has strong rural health needs, especially in western Kansas. Most rural communities are designated HPSAs. The state processes applications efficiently.",
    websiteUrl: "https://www.kdhe.ks.gov",
  },
  KY: {
    stateCode: "KY",
    stateName: "Kentucky",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Kentucky Cabinet for Health and Family Services sponsors applications.",
    tips: "Kentucky has significant needs in Appalachian eastern Kentucky. Rural communities have strong demand for primary care. The state has been supportive of IMG physicians.",
    websiteUrl: "https://chfs.ky.gov",
  },
  LA: {
    stateCode: "LA",
    stateName: "Louisiana",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Louisiana Department of Health sponsors Conrad 30 applications.",
    tips: "Louisiana has strong rural health needs throughout the state. Northern Louisiana parishes and rural Acadiana have highest demand. The state has a history of supporting IMG physicians.",
    websiteUrl: "https://ldh.la.gov",
  },
  ME: {
    stateCode: "ME",
    stateName: "Maine",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Maine Department of Health and Human Services sponsors applications.",
    tips: "Maine has significant rural health needs, especially in northern and western regions. Aging population creates strong demand for primary care. Generally IMG-friendly.",
    websiteUrl: "https://www.maine.gov/dhhs",
  },
  MD: {
    stateCode: "MD",
    stateName: "Maryland",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Maryland Department of Health administers the Conrad 30 program.",
    tips: "Maryland has both urban underserved areas (Baltimore) and rural areas (Eastern Shore, Western Maryland). FQHCs in Baltimore are common placements. Moderate competition.",
    websiteUrl: "https://health.maryland.gov",
  },
  MA: {
    stateCode: "MA",
    stateName: "Massachusetts",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "8-15 months",
    processingTime: "90-120 days",
    priorityAreas: ["Primary Care", "Community Health Centers"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Massachusetts Department of Public Health sponsors applications. Competitive due to large medical community.",
    tips: "Massachusetts is competitive. Community health centers in Springfield, Worcester, and Boston neighborhoods are common placements. Strong academic medical community can be an advantage for networking.",
    websiteUrl: "https://www.mass.gov/dph",
  },
  MI: {
    stateCode: "MI",
    stateName: "Michigan",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Underserved Areas", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Michigan Department of Health and Human Services sponsors Conrad 30 applications. Strong focus on underserved communities.",
    tips: "Michigan is one of the most IMG-friendly states. Strong opportunities in Detroit, Flint, and rural Upper Peninsula. The state has a long history of supporting international medical graduates. Apply through MDHHS.",
    websiteUrl: "https://www.michigan.gov/mdhhs",
  },
  MN: {
    stateCode: "MN",
    stateName: "Minnesota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Minnesota Department of Health sponsors applications.",
    tips: "Minnesota has rural health needs outside the Twin Cities metro. Southern and western Minnesota communities have strong demand. The state has good support systems for new physicians.",
    websiteUrl: "https://www.health.state.mn.us",
  },
  MS: {
    stateCode: "MS",
    stateName: "Mississippi",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Delta Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "OB/GYN", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Mississippi State Department of Health sponsors Conrad 30 applications.",
    tips: "Mississippi has among the highest physician shortage in the nation. The Delta region has critical need. Less competitive for waivers. Strong demand across nearly all specialties in rural areas.",
    websiteUrl: "https://msdh.ms.gov",
  },
  MO: {
    stateCode: "MO",
    stateName: "Missouri",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Missouri Department of Health and Senior Services sponsors applications.",
    tips: "Missouri has strong rural health needs in the Ozarks and Bootheel region. Kansas City and St. Louis metro areas have some HPSA-designated sites. The state processes applications reasonably quickly.",
    websiteUrl: "https://health.mo.gov",
  },
  MT: {
    stateCode: "MT",
    stateName: "Montana",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Frontier Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Montana Department of Public Health and Human Services sponsors applications.",
    tips: "Montana has widespread rural and frontier health needs. Most communities outside Billings and Missoula are designated HPSAs. Expect rural lifestyle. Indian Health Service facilities are common placements.",
    websiteUrl: "https://dphhs.mt.gov",
  },
  NE: {
    stateCode: "NE",
    stateName: "Nebraska",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Nebraska Department of Health and Human Services sponsors Conrad 30 applications.",
    tips: "Nebraska has strong rural health needs throughout western and central regions. Most communities outside Omaha and Lincoln qualify. The state has been supportive of IMG physicians.",
    websiteUrl: "https://dhhs.ne.gov",
  },
  NV: {
    stateCode: "NV",
    stateName: "Nevada",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Nevada Division of Public and Behavioral Health sponsors applications.",
    tips: "Nevada has significant physician shortages statewide. Rural Nevada has critical needs. Las Vegas and Reno have some HPSA-designated sites. Growing state with increasing demand.",
    websiteUrl: "https://dpbh.nv.gov",
  },
  NH: {
    stateCode: "NH",
    stateName: "New Hampshire",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. New Hampshire Department of Health and Human Services sponsors applications.",
    tips: "New Hampshire has rural health needs in the northern part of the state. Smaller applicant pool means less competition. Community health centers are common placements.",
    websiteUrl: "https://www.dhhs.nh.gov",
  },
  NJ: {
    stateCode: "NJ",
    stateName: "New Jersey",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-15 months",
    processingTime: "90-120 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Community Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. New Jersey Department of Health sponsors Conrad 30 applications. Competitive due to proximity to NYC.",
    tips: "New Jersey is moderately competitive. Urban underserved areas in Newark, Camden, and Trenton have strong need. FQHCs are preferred placement sites. Strong IMG community in the state.",
    websiteUrl: "https://www.nj.gov/health",
  },
  NM: {
    stateCode: "NM",
    stateName: "New Mexico",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Emergency Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. New Mexico Department of Health sponsors applications. Tribal health facilities are common placements.",
    tips: "New Mexico has critical physician shortages statewide. Indian Health Service and tribal facilities offer unique opportunities. Rural communities have high demand. The state is generally IMG-friendly.",
    websiteUrl: "https://www.nmhealth.org",
  },
  NY: {
    stateCode: "NY",
    stateName: "New York",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "12-24 months",
    processingTime: "120-180 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. New York State Department of Health administers the Conrad 30 program. Very competitive — one of the most sought-after states.",
    tips: "New York is extremely competitive with long processing times. Upstate rural areas have better chances than NYC metro. FQHCs and community health centers in the Bronx, Brooklyn, and Buffalo are common placements. Apply very early and have backup states.",
    websiteUrl: "https://www.health.ny.gov",
  },
  NC: {
    stateCode: "NC",
    stateName: "North Carolina",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. North Carolina Department of Health and Human Services sponsors applications.",
    tips: "North Carolina has strong rural health needs in eastern and western mountain communities. Growing state with increasing demand. Community health centers and rural hospitals are common placements.",
    websiteUrl: "https://www.ncdhhs.gov",
  },
  ND: {
    stateCode: "ND",
    stateName: "North Dakota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. North Dakota Department of Health sponsors Conrad 30 applications.",
    tips: "North Dakota has widespread rural health needs. Most communities outside Fargo and Bismarck qualify. Fast processing times. Less competitive than larger states. Oil country (western ND) has growing populations.",
    websiteUrl: "https://www.health.nd.gov",
  },
  OH: {
    stateCode: "OH",
    stateName: "Ohio",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Ohio Department of Health administers the Conrad 30 program. One of the most IMG-friendly states.",
    tips: "Ohio is one of the best states for IMG physicians. Strong opportunities in Cleveland, Dayton, Columbus suburbs, and rural Appalachian counties. The state has a large IMG community and well-established support systems. Reasonable processing times.",
    websiteUrl: "https://odh.ohio.gov",
  },
  OK: {
    stateCode: "OK",
    stateName: "Oklahoma",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Oklahoma State Department of Health sponsors Conrad 30 applications.",
    tips: "Oklahoma has significant rural health needs throughout the state. Tribal health facilities offer additional opportunities. Western and southeastern Oklahoma have the greatest need.",
    websiteUrl: "https://oklahoma.gov/health",
  },
  OR: {
    stateCode: "OR",
    stateName: "Oregon",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Oregon Health Authority sponsors Conrad 30 applications.",
    tips: "Oregon has strong rural health needs east of the Cascades. Behavioral health is a priority statewide. Portland metro is more competitive. Eastern Oregon communities have critical shortages.",
    websiteUrl: "https://www.oregon.gov/oha",
  },
  PA: {
    stateCode: "PA",
    stateName: "Pennsylvania",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Urban Underserved"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Pennsylvania Department of Health administers the Conrad 30 program.",
    tips: "Pennsylvania has opportunities in both rural areas (north-central PA, coal country) and urban underserved communities (Philadelphia, Pittsburgh neighborhoods). Strong medical infrastructure. IMG-friendly with established communities.",
    websiteUrl: "https://www.health.pa.gov",
  },
  RI: {
    stateCode: "RI",
    stateName: "Rhode Island",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Community Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Rhode Island Department of Health sponsors applications.",
    tips: "Rhode Island is a small state with limited waiver demand. Providence and surrounding communities have HPSA-designated sites. Less competitive than neighboring Massachusetts and Connecticut.",
    websiteUrl: "https://health.ri.gov",
  },
  SC: {
    stateCode: "SC",
    stateName: "South Carolina",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. South Carolina Department of Health and Environmental Control sponsors applications.",
    tips: "South Carolina has significant rural health needs, especially in the Pee Dee region and Lowcountry. The state has been increasingly welcoming to IMG physicians. FQHCs and rural hospitals are common placements.",
    websiteUrl: "https://scdhec.gov",
  },
  SD: {
    stateCode: "SD",
    stateName: "South Dakota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. South Dakota Department of Health sponsors Conrad 30 applications.",
    tips: "South Dakota has widespread rural health needs. Indian Health Service facilities on reservations offer unique opportunities. Fast processing times. Less competitive than larger states.",
    websiteUrl: "https://doh.sd.gov",
  },
  TN: {
    stateCode: "TN",
    stateName: "Tennessee",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Tennessee Department of Health sponsors Conrad 30 applications.",
    tips: "Tennessee has strong rural health needs in East Tennessee (Appalachian) and West Tennessee. Nashville and Memphis metro have some HPSA sites. The state has good support for IMG physicians.",
    websiteUrl: "https://www.tn.gov/health",
  },
  TX: {
    stateCode: "TX",
    stateName: "Texas",
    conradSlots: 30,
    flexSlots: 15,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Border Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Texas Department of State Health Services administers the Conrad 30 program. One of the most active waiver states with additional flex slots.",
    tips: "Texas is one of the best states for J-1 waivers. Large number of opportunities across the state. Rio Grande Valley, West Texas, and East Texas have highest need. Family medicine is the most in-demand specialty. The state has a massive IMG community and excellent support networks.",
    websiteUrl: "https://www.dshs.texas.gov",
  },
  UT: {
    stateCode: "UT",
    stateName: "Utah",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Utah Department of Health and Human Services sponsors Conrad 30 applications.",
    tips: "Utah has rural health needs in southern and eastern parts of the state. Rural communities outside Salt Lake City and Provo have the greatest need. Growing population creates increasing demand.",
    websiteUrl: "https://dhhs.utah.gov",
  },
  VT: {
    stateCode: "VT",
    stateName: "Vermont",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Vermont Department of Health sponsors applications.",
    tips: "Vermont has widespread rural health needs. The Northeast Kingdom and southern Vermont have the greatest shortages. Small state with limited applications — less competitive. Community health centers are common placements.",
    websiteUrl: "https://www.healthvermont.gov",
  },
  VA: {
    stateCode: "VA",
    stateName: "Virginia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Virginia Department of Health sponsors Conrad 30 applications.",
    tips: "Virginia has strong rural health needs in southwestern Appalachian Virginia and the Southside region. Northern Virginia is very competitive. Rural areas have better chances. The state has an established IMG community.",
    websiteUrl: "https://www.vdh.virginia.gov",
  },
  WA: {
    stateCode: "WA",
    stateName: "Washington",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Washington State Department of Health sponsors Conrad 30 applications.",
    tips: "Washington has rural health needs east of the Cascades. Eastern Washington and rural Olympic Peninsula have the greatest need. Seattle metro is very competitive. Behavioral health is a statewide priority.",
    websiteUrl: "https://doh.wa.gov",
  },
  WV: {
    stateCode: "WV",
    stateName: "West Virginia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. West Virginia Department of Health and Human Resources sponsors applications.",
    tips: "West Virginia has some of the highest physician shortage rates in the country. Nearly the entire state is designated HPSA. Fast processing times. Very IMG-friendly. Strong demand for primary care across all communities.",
    websiteUrl: "https://dhhr.wv.gov",
  },
  WI: {
    stateCode: "WI",
    stateName: "Wisconsin",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Wisconsin Department of Health Services sponsors Conrad 30 applications.",
    tips: "Wisconsin has rural health needs in northern and western regions. Marshfield Clinic system has historically been a major employer of IMG physicians. Community health centers and critical access hospitals are common placements.",
    websiteUrl: "https://www.dhs.wisconsin.gov",
  },
  WY: {
    stateCode: "WY",
    stateName: "Wyoming",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Frontier Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Wyoming Department of Health sponsors Conrad 30 applications.",
    tips: "Wyoming has the smallest population of any state but significant rural health needs. Nearly all communities are designated HPSAs. Very fast processing. Least competitive state for waivers. Expect rural lifestyle.",
    websiteUrl: "https://health.wyo.gov",
  },
};

export function getWaiverStateByCode(code: string): WaiverState | null {
  return WAIVER_STATES[code.toUpperCase()] || null;
}

export function getWaiverStateBySlug(slug: string): WaiverState | null {
  const entry = Object.values(WAIVER_STATES).find(
    (s) => s.stateName.toLowerCase().replace(/\s+/g, "-") === slug.toLowerCase()
  );
  return entry || null;
}

export function getAllWaiverStateSlugs(): { state: string }[] {
  return Object.values(WAIVER_STATES).map((s) => ({
    state: s.stateName.toLowerCase().replace(/\s+/g, "-"),
  }));
}
