export interface WaiverState {
  stateCode: string;
  stateName: string;
  conradSlots: number;
  flexSlots: number;
  timeline: string;
  processingTime: string;
  priorityAreas: string[];
  specialtyNeeds: string[];
  requirements: string;
  tips: string;
  websiteUrl: string;
  /** Data confidence: "official" = from state DOH/3RNET, "community" = from physician reports, "estimated" = based on available data */
  confidence?: "official" | "community" | "estimated";
  /** When was this state's data last verified */
  lastVerified?: string;
}

export const WAIVER_STATES: Record<string, WaiverState> = {
  AL: {
    stateCode: "AL",
    stateName: "Alabama",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a federally designated HPSA or MUA for 3 years. Alabama Department of Public Health sponsors J-1 waiver applications through the Conrad 30 program.",
    tips: "Alabama has strong demand in rural counties. Applications through the Alabama Department of Public Health are typically processed within 60-90 days. Apply early in the federal fiscal year (October).",
    websiteUrl: "https://www.alabamapublichealth.gov",
  },
  AK: {
    stateCode: "AK",
    stateName: "Alaska",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must serve in a designated HPSA or MUA. Alaska Department of Health sponsors Conrad 30 applications. Tribal health facilities are common placement sites.",
    tips: "Alaska has unique opportunities in tribal and native health facilities. Remote locations may offer higher compensation. Contact the Alaska State Medical Association for guidance.",
    websiteUrl: "https://health.alaska.gov",
  },
  AZ: {
    stateCode: "AZ",
    stateName: "Arizona",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-9 months",
    processingTime: "45-90 days",
    priorityAreas: ["Primary Care", "Behavioral Health", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Arizona ADHS administers the Conrad 30 program. Important: Arizona does NOT offer flex waiver slots — all 30 must be in designated shortage areas. Arizona fills all 30 slots annually. Preference given to primary care and behavioral health.",
    tips: "Arizona fills all 30 Conrad slots every year. Strong demand in Maricopa County suburbs and rural areas. Behavioral health specialists are especially needed. Consider SCRC (Southeast Crescent Regional Commission) or HHS Clinical Care Waiver as alternatives. Apply through ADHS as early as October 1.",
    websiteUrl: "https://www.azdhs.gov",
  },
  AR: {
    stateCode: "AR",
    stateName: "Arkansas",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must practice in a federally designated HPSA or MUA for 3 years. Arkansas Department of Health reviews and sponsors applications.",
    tips: "Arkansas has significant rural health needs. Delta region communities offer strong opportunities. The state is generally IMG-friendly with reasonable processing times.",
    websiteUrl: "https://www.healthy.arkansas.gov",
  },
  CA: {
    stateCode: "CA",
    stateName: "California",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-18 months (one of the longest in the nation)",
    processingTime: "90-180 days — HCAI reviews are thorough and slow",
    priorityAreas: ["Primary Care", "HPSA Focus", "Community Health Centers", "Federally Qualified Health Centers"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. California HCAI (Department of Health Care Access and Information) administers the program. Strong preference for FQHC placements. California requires employers to demonstrate inability to recruit a US physician for 6+ months. HPSA score of 14+ recommended for competitive applications. State requires full California medical license at time of application.",
    tips: "California is the most competitive Conrad 30 state — slots typically fill by January/February of each fiscal year (which starts October 1). FQHC and community health center placements have significantly better approval rates than private practice. Central Valley (Fresno, Bakersfield, Stockton) and rural Northern California (Redding, Eureka) have highest need and best chances. Inland Empire (San Bernardino, Riverside) is growing rapidly with physician shortages. Avoid applying for urban LA or SF Bay Area placements — extremely competitive and often denied. Apply as early as October 1 as possible. Budget for California's high cost of living when evaluating offers.",
    websiteUrl: "https://hcai.ca.gov",
  },
  CO: {
    stateCode: "CO",
    stateName: "Colorado",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine"],
    requirements:
      "Must serve in a designated HPSA or MUA. Colorado Department of Public Health and Environment sponsors applications. 3-year service commitment required.",
    tips: "Colorado has growing demand especially on the Eastern Plains and Western Slope. Behavioral health specialists are in particularly high demand. Denver metro HPSA sites are competitive.",
    websiteUrl: "https://cdphe.colorado.gov",
  },
  CT: {
    stateCode: "CT",
    stateName: "Connecticut",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Community Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a designated HPSA or MUA for 3 years. Connecticut Department of Public Health administers the program.",
    tips: "Connecticut has urban underserved areas in Hartford, Bridgeport, and New Haven with strong need. Community health centers are common placement sites.",
    websiteUrl: "https://portal.ct.gov/dph",
  },
  DE: {
    stateCode: "DE",
    stateName: "Delaware",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Delaware Division of Public Health sponsors Conrad 30 applications.",
    tips: "Delaware is a small state with limited slots used each year. Southern Delaware (Sussex County) has the greatest need. Less competitive than neighboring states.",
    websiteUrl: "https://dhss.delaware.gov/dph",
  },
  FL: {
    stateCode: "FL",
    stateName: "Florida",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-15 months (competitive, plan early)",
    processingTime: "90-120 days — DOH review can be thorough for competitive applications",
    priorityAreas: ["Primary Care", "Rural Health", "HPSA", "Behavioral Health", "Geriatrics"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "Geriatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Florida DOH administers the Conrad 30 program. Florida is highly competitive due to desirable lifestyle and large IMG population. HPSA score of 14+ strongly recommended. Employer must demonstrate inability to recruit US physicians. Full unrestricted Florida medical license required. Florida also participates in ARC (Appalachian Regional Commission) waivers for eligible panhandle counties.",
    tips: "Florida is very competitive — second only to California and New York in demand. No state income tax is a major draw. Best chances are in rural panhandle counties (Gadsden, Jackson, Bay), central Florida agricultural areas (Polk, Highlands, Hardee), and the northern tier (Marion, Putnam, Baker). South Florida (Miami-Dade, Broward, Palm Beach) is extremely competitive — avoid unless you have a very high HPSA score. Geriatrics is a growing need due to Florida's aging population. FQHCs in rural areas have best approval rates. Large IMG community statewide — network at Florida Medical Association IMG sections. Apply in October as early as possible.",
    websiteUrl: "https://www.floridahealth.gov",
  },
  GA: {
    stateCode: "GA",
    stateName: "Georgia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Georgia Department of Community Health sponsors Conrad 30 applications.",
    tips: "Georgia has significant rural health needs, especially in southern and eastern regions. Atlanta metro has some HPSA-designated sites. The state has been increasingly IMG-friendly.",
    websiteUrl: "https://dch.georgia.gov",
  },
  HI: {
    stateCode: "HI",
    stateName: "Hawaii",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Islands", "Native Hawaiian Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Hawaii Department of Health sponsors applications. Neighbor islands have greatest need.",
    tips: "Hawaii has unique opportunities on neighbor islands (Big Island, Maui, Kauai, Molokai). Cost of living is high but some employers provide housing assistance. Limited number of applications each year.",
    websiteUrl: "https://health.hawaii.gov",
  },
  ID: {
    stateCode: "ID",
    stateName: "Idaho",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Idaho Department of Health and Welfare sponsors applications.",
    tips: "Idaho has strong rural health needs throughout the state. Boise metro is more competitive. Eastern and central Idaho have the greatest need. Generally IMG-friendly.",
    websiteUrl: "https://healthandwelfare.idaho.gov",
  },
  IL: {
    stateCode: "IL",
    stateName: "Illinois",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months (moderate competitiveness)",
    processingTime: "60-90 days — IDPH is reasonably efficient",
    priorityAreas: ["Primary Care", "Rural Health", "Urban Underserved", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Illinois DPH (Department of Public Health) administers the Conrad 30 program. HPSA score of 10+ recommended. Illinois has a large residency training infrastructure — many waiver physicians trained in-state. Full Illinois medical license required. The state also accepts applications through HHS Clinical Care Waivers (unlimited slots, HPSA score 7+ required) for eligible sites.",
    tips: "Illinois offers a mix of urban and rural waiver opportunities. Downstate Illinois (Peoria, Springfield, Champaign-Urbana, Carbondale, Rockford) is significantly less competitive than Chicago. Chicago's south side and west side FQHCs have strong track records for waiver placements. Cook County Health System has historically been a major waiver employer. East St. Louis has critical needs. Large IMG physician community — network through Illinois State Medical Society IMG section. Consider that Illinois has a relatively high state income tax (4.95% flat rate).",
    websiteUrl: "https://dph.illinois.gov",
  },
  IN: {
    stateCode: "IN",
    stateName: "Indiana",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Indiana ISDH administers the program. Important: Indiana does NOT offer flex waiver slots. Indiana fills all 30 slots annually.",
    tips: "Indiana fills all 30 Conrad slots every year and does not support flex waivers. Southern Indiana and rural counties have highest demand. Community health centers are common placements. Consider ARC waiver for eligible Appalachian southern Indiana counties as an alternative pathway.",
    websiteUrl: "https://www.in.gov/health",
  },
  IA: {
    stateCode: "IA",
    stateName: "Iowa",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Iowa Department of Public Health sponsors Conrad 30 applications.",
    tips: "Iowa has widespread rural health needs. Most counties outside Des Moines metro qualify. The state is generally welcoming to IMGs. Community hospitals and FQHCs are common placements.",
    websiteUrl: "https://hhs.iowa.gov",
  },
  KS: {
    stateCode: "KS",
    stateName: "Kansas",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Kansas Department of Health and Environment administers the program.",
    tips: "Kansas has strong rural health needs, especially in western Kansas. Most rural communities are designated HPSAs. The state processes applications efficiently.",
    websiteUrl: "https://www.kdhe.ks.gov",
  },
  KY: {
    stateCode: "KY",
    stateName: "Kentucky",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Kentucky Cabinet for Health and Family Services sponsors applications.",
    tips: "Kentucky has significant needs in Appalachian eastern Kentucky. Rural communities have strong demand for primary care. The state has been supportive of IMG physicians.",
    websiteUrl: "https://chfs.ky.gov",
  },
  LA: {
    stateCode: "LA",
    stateName: "Louisiana",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Louisiana Department of Health sponsors Conrad 30 applications.",
    tips: "Louisiana has strong rural health needs throughout the state. Northern Louisiana parishes and rural Acadiana have highest demand. The state has a history of supporting IMG physicians.",
    websiteUrl: "https://ldh.la.gov",
  },
  ME: {
    stateCode: "ME",
    stateName: "Maine",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Maine Department of Health and Human Services sponsors applications.",
    tips: "Maine has significant rural health needs, especially in northern and western regions. Aging population creates strong demand for primary care. Generally IMG-friendly.",
    websiteUrl: "https://www.maine.gov/dhhs",
  },
  MD: {
    stateCode: "MD",
    stateName: "Maryland",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Maryland Department of Health administers the Conrad 30 program.",
    tips: "Maryland has both urban underserved areas (Baltimore) and rural areas (Eastern Shore, Western Maryland). FQHCs in Baltimore are common placements. Moderate competition.",
    websiteUrl: "https://health.maryland.gov",
  },
  MA: {
    stateCode: "MA",
    stateName: "Massachusetts",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "8-15 months",
    processingTime: "90-120 days",
    priorityAreas: ["Primary Care", "Community Health Centers"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Massachusetts Department of Public Health sponsors applications. Competitive due to large medical community.",
    tips: "Massachusetts is competitive. Community health centers in Springfield, Worcester, and Boston neighborhoods are common placements. Strong academic medical community can be an advantage for networking.",
    websiteUrl: "https://www.mass.gov/dph",
  },
  MI: {
    stateCode: "MI",
    stateName: "Michigan",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-10 months (efficient, IMG-friendly process)",
    processingTime: "45-75 days — MDHHS is responsive and organized",
    priorityAreas: ["Primary Care", "Underserved Areas", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Michigan DHHS sponsors Conrad 30 applications. HPSA score of 7+ typically sufficient. Michigan has one of the most IMG-friendly medical licensing processes in the nation. Full Michigan medical license required. Michigan also participates in HHS Clinical Care Waivers (unlimited slots, HPSA score 7+ required) for eligible sites.",
    tips: "Michigan fills all 30 Conrad slots every single year — one of only 3 states (with Kentucky and New York) that has never had unused slots in 20+ years of data. Despite high competition, Michigan remains a top-5 state for IMG physicians. Detroit has massive physician shortages — Beaumont, Henry Ford, DMC/Tenet systems are major waiver employers. Flint and Saginaw have critical needs. Upper Peninsula is severely underserved with high HPSA scores. Also consider HHS Clinical Care Waiver (unlimited slots) or ARC waiver for eligible counties as alternatives when Conrad slots fill. Michigan has a strong H-1B cap-exempt hospital base (University of Michigan, Beaumont, Henry Ford, Spectrum Health). State income tax is flat 4.25%.",
    websiteUrl: "https://www.michigan.gov/mdhhs",
  },
  MN: {
    stateCode: "MN",
    stateName: "Minnesota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Minnesota Department of Health sponsors applications.",
    tips: "Minnesota has rural health needs outside the Twin Cities metro. Southern and western Minnesota communities have strong demand. The state has good support systems for new physicians.",
    websiteUrl: "https://www.health.state.mn.us",
  },
  MS: {
    stateCode: "MS",
    stateName: "Mississippi",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Delta Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "OB/GYN", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Mississippi State Department of Health sponsors Conrad 30 applications.",
    tips: "Mississippi has among the highest physician shortage in the nation. The Delta region has critical need. Less competitive for waivers. Strong demand across nearly all specialties in rural areas.",
    websiteUrl: "https://msdh.ms.gov",
  },
  MO: {
    stateCode: "MO",
    stateName: "Missouri",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Missouri Department of Health and Senior Services sponsors applications.",
    tips: "Missouri has strong rural health needs in the Ozarks and Bootheel region. Kansas City and St. Louis metro areas have some HPSA-designated sites. The state processes applications reasonably quickly.",
    websiteUrl: "https://health.mo.gov",
  },
  MT: {
    stateCode: "MT",
    stateName: "Montana",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Frontier Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Montana Department of Public Health and Human Services sponsors applications.",
    tips: "Montana has widespread rural and frontier health needs. Most communities outside Billings and Missoula are designated HPSAs. Expect rural lifestyle. Indian Health Service facilities are common placements.",
    websiteUrl: "https://dphhs.mt.gov",
  },
  NE: {
    stateCode: "NE",
    stateName: "Nebraska",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Nebraska Department of Health and Human Services sponsors Conrad 30 applications.",
    tips: "Nebraska has strong rural health needs throughout western and central regions. Most communities outside Omaha and Lincoln qualify. The state has been supportive of IMG physicians.",
    websiteUrl: "https://dhhs.ne.gov",
  },
  NV: {
    stateCode: "NV",
    stateName: "Nevada",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Nevada Division of Public and Behavioral Health sponsors applications.",
    tips: "Nevada has significant physician shortages statewide. Rural Nevada has critical needs. Las Vegas and Reno have some HPSA-designated sites. Growing state with increasing demand.",
    websiteUrl: "https://dpbh.nv.gov",
  },
  NH: {
    stateCode: "NH",
    stateName: "New Hampshire",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. New Hampshire Department of Health and Human Services sponsors applications.",
    tips: "New Hampshire has rural health needs in the northern part of the state. Smaller applicant pool means less competition. Community health centers are common placements.",
    websiteUrl: "https://www.dhhs.nh.gov",
  },
  NJ: {
    stateCode: "NJ",
    stateName: "New Jersey",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-15 months (competitive, similar to NY process)",
    processingTime: "90-120 days — NJ DOH is thorough but not fast",
    priorityAreas: ["Primary Care", "Urban Underserved", "Community Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. NJ DOH sponsors Conrad 30 applications. Competitive due to desirable location (NYC metro proximity) and large IMG population. HPSA score of 12+ recommended for competitive applications. Full unrestricted NJ medical license required. Employer must demonstrate inability to recruit US physicians.",
    tips: "New Jersey is moderately to highly competitive — proximity to NYC makes it desirable. Best chances are in urban underserved areas: Newark, Camden, Trenton, Paterson, Elizabeth, and Atlantic City. FQHCs in these cities have strong approval track records. South Jersey rural areas have growing need. NJ has no flex slots beyond Conrad 30 — so exactly 30 slots per year. Large and well-organized IMG community — NJ Medical Society has IMG-specific resources. NJ has a graduated state income tax (1.4-10.75%) — high earners pay more. Consider NJ as a backup to NY — similar geography, somewhat less competitive process.",
    websiteUrl: "https://www.nj.gov/health",
  },
  NM: {
    stateCode: "NM",
    stateName: "New Mexico",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Emergency Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. New Mexico Department of Health sponsors applications. Tribal health facilities are common placements.",
    tips: "New Mexico has critical physician shortages statewide. Indian Health Service and tribal facilities offer unique opportunities. Rural communities have high demand. The state is generally IMG-friendly.",
    websiteUrl: "https://www.nmhealth.org",
  },
  NY: {
    stateCode: "NY",
    stateName: "New York",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "12-24 months (longest in nation — plan accordingly)",
    processingTime: "120-180+ days — NYS DOH is notoriously slow; some cases take 6+ months for state processing alone before federal DOS submission",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. NYS Department of Health administers the program. Extremely competitive — all 30 slots plus flex slots typically fill within weeks of October 1. Employers must demonstrate active recruitment of US physicians for 6+ months. HPSA score matters — higher scores get priority. Full unrestricted NY medical license required at time of Conrad 30 application. New York also accepts applications through USDA and HHS waiver pathways as alternatives.",
    tips: "New York is the most competitive waiver state. Slots fill within the first 2-3 weeks of the federal fiscal year (October 1). If you miss the window, you wait an entire year. Upstate New York (Buffalo, Syracuse, Albany, Adirondack region) has significantly better chances than NYC metro. NYC boroughs (Bronx, Brooklyn) are possible through FQHCs but extremely competitive. Consider USDA or HHS waiver pathways as alternatives to Conrad 30. Always have 2-3 backup states ready. Start your employer search 12+ months before your J-1 waiver deadline. Budget $5,000-15,000 for immigration attorney fees in NY (complex state process).",
    websiteUrl: "https://www.health.ny.gov",
  },
  NC: {
    stateCode: "NC",
    stateName: "North Carolina",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months (moderate, growing demand)",
    processingTime: "60-90 days — NC DHHS is reasonably efficient",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health", "Maternal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. NC DHHS sponsors applications. HPSA score of 7+ typically sufficient. Full unrestricted NC medical license required. NC also participates in ARC (Appalachian Regional Commission) waivers for eligible western mountain counties. SCRC (Southeast Crescent Regional Commission) waivers available for eligible eastern counties.",
    tips: "North Carolina is a growing state with increasing physician demand. Eastern NC (Greenville, Rocky Mount, Wilson, Lumberton) has critical rural health needs and the highest HPSA scores. Western mountain communities (Asheville area, Appalachian counties) qualify for ARC waivers — giving additional slots beyond Conrad 30. Charlotte and Raleigh-Durham suburbs have growing HPSA-designated sites but are more competitive. NC has a large residency training infrastructure (Duke, UNC, Wake Forest, ECU) — many graduates stay in-state. Reasonable cost of living. State income tax is flat 4.5% (recently reduced). Growing IMG community statewide. Community health centers in eastern NC and mountain communities have best approval rates.",
    websiteUrl: "https://www.ncdhhs.gov",
  },
  ND: {
    stateCode: "ND",
    stateName: "North Dakota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. North Dakota Department of Health sponsors Conrad 30 applications.",
    tips: "North Dakota has widespread rural health needs. Most communities outside Fargo and Bismarck qualify. Fast processing times. Less competitive than larger states. Oil country (western ND) has growing populations.",
    websiteUrl: "https://www.health.nd.gov",
  },
  OH: {
    stateCode: "OH",
    stateName: "Ohio",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-10 months (one of the most IMG-friendly processes)",
    processingTime: "45-75 days — ODH is responsive and well-organized",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health", "Behavioral Health", "Appalachian Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Ohio Department of Health (ODH) administers the Conrad 30 program. Ohio is widely considered one of the most IMG-friendly states in the nation. HPSA score of 7+ typically sufficient. Ohio also participates in ARC (Appalachian Regional Commission) waivers for eligible Appalachian counties — this provides additional slots beyond Conrad 30. Full unrestricted Ohio medical license required.",
    tips: "Ohio is a top-tier choice for J-1 waiver physicians. Reasonable cost of living, no extreme weather by physician standards, and a massive IMG physician community. Appalachian counties in southeast Ohio (Athens, Vinton, Meigs, Gallia) have critical needs and highest HPSA scores. Cleveland metro has multiple FQHC placements. Dayton, Youngstown, and Toledo have strong hospital-based waiver positions. Columbus suburbs are growing with new HPSA designations. ARC waiver pathway gives Ohio effectively more than 30 total slots. The Ohio State Medical Association has an active IMG section. Ohio has a moderate state income tax (0-3.75% graduated). Strong H-1B cap-exempt employer base (Cleveland Clinic, Ohio State, UC Health, MetroHealth).",
    websiteUrl: "https://odh.ohio.gov",
  },
  OK: {
    stateCode: "OK",
    stateName: "Oklahoma",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Oklahoma State Department of Health sponsors Conrad 30 applications.",
    tips: "Oklahoma has significant rural health needs throughout the state. Tribal health facilities offer additional opportunities. Western and southeastern Oklahoma have the greatest need.",
    websiteUrl: "https://oklahoma.gov/health",
  },
  OR: {
    stateCode: "OR",
    stateName: "Oregon",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Oregon Health Authority sponsors Conrad 30 applications.",
    tips: "Oregon has strong rural health needs east of the Cascades. Behavioral health is a priority statewide. Portland metro is more competitive. Eastern Oregon communities have critical shortages.",
    websiteUrl: "https://www.oregon.gov/oha",
  },
  PA: {
    stateCode: "PA",
    stateName: "Pennsylvania",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months (moderate competitiveness)",
    processingTime: "60-90 days — PA DOH is reasonably efficient",
    priorityAreas: ["Primary Care", "Rural Health", "Urban Underserved", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. PA DOH administers the Conrad 30 program. HPSA score of 7+ typically sufficient. Full unrestricted PA medical license required. Pennsylvania also participates in ARC waivers for eligible Appalachian counties (covers much of central and western PA). HHS Clinical Care Waivers (unlimited slots) available for qualifying sites with HPSA score 7+.",
    tips: "Pennsylvania offers a strong mix of urban and rural waiver opportunities. Philadelphia has major FQHC networks with established waiver relationships (Philadelphia Health Centers, Project HOME). Pittsburgh's underserved neighborhoods have strong need. North-central PA (Williamsport, Lock Haven, Sunbury) and coal country (Scranton, Wilkes-Barre) are severely underserved with high HPSA scores. ARC waiver pathway is a significant advantage — many PA counties qualify, giving effectively more than 30 slots. PA has massive medical training infrastructure (Penn, Jefferson, Temple, Drexel, Pittsburgh, Geisinger). Large IMG community — PA Medical Society supports IMG integration. State income tax is flat 3.07% (one of the lowest with income tax). Cost of living is very reasonable outside Philadelphia.",
    websiteUrl: "https://www.health.pa.gov",
  },
  RI: {
    stateCode: "RI",
    stateName: "Rhode Island",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Community Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Rhode Island Department of Health sponsors applications.",
    tips: "Rhode Island is a small state with limited waiver demand. Providence and surrounding communities have HPSA-designated sites. Less competitive than neighboring Massachusetts and Connecticut.",
    websiteUrl: "https://health.ri.gov",
  },
  SC: {
    stateCode: "SC",
    stateName: "South Carolina",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. South Carolina Department of Health and Environmental Control sponsors applications.",
    tips: "South Carolina has significant rural health needs, especially in the Pee Dee region and Lowcountry. The state has been increasingly welcoming to IMG physicians. FQHCs and rural hospitals are common placements.",
    websiteUrl: "https://scdhec.gov",
  },
  SD: {
    stateCode: "SD",
    stateName: "South Dakota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. South Dakota Department of Health sponsors Conrad 30 applications.",
    tips: "South Dakota has widespread rural health needs. Indian Health Service facilities on reservations offer unique opportunities. Fast processing times. Less competitive than larger states.",
    websiteUrl: "https://doh.sd.gov",
  },
  TN: {
    stateCode: "TN",
    stateName: "Tennessee",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Tennessee Department of Health sponsors Conrad 30 applications.",
    tips: "Tennessee has strong rural health needs in East Tennessee (Appalachian) and West Tennessee. Nashville and Memphis metro have some HPSA sites. The state has good support for IMG physicians.",
    websiteUrl: "https://www.tn.gov/health",
  },
  TX: {
    stateCode: "TX",
    stateName: "Texas",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-10 months (faster than most large states)",
    processingTime: "45-75 days — DSHS is one of the more efficient state agencies",
    priorityAreas: ["Primary Care", "Rural Health", "Border Health", "Behavioral Health", "Maternal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Texas DSHS (Department of State Health Services) administers the Conrad 30 program. Important: Texas does NOT offer flex waiver slots — all 30 must be in designated shortage areas. No state income tax. Employer must be in a HPSA or MUA. Texas accepts specialists beyond primary care more readily than most states. Full unrestricted Texas medical license required.",
    tips: "Texas is widely considered one of the best states for J-1 waivers despite having no flex slots. All 30 slots fill very quickly — often within the first days of the fiscal year (October 1). No state income tax makes Texas financially attractive. Rio Grande Valley, West Texas (El Paso, Lubbock, Midland-Odessa), and East Texas (Tyler, Longview, Texarkana) have the highest HPSA scores and need. Dallas-Fort Worth and Houston suburbs have growing HPSA-designated sites. Also consider HHS Clinical Care Waiver (unlimited slots, requires HPSA score 7+) as alternative to Conrad 30. Texas has one of the largest IMG physician communities in the US. Start employer search 8-10 months before your waiver deadline.",
    websiteUrl: "https://www.dshs.texas.gov",
  },
  UT: {
    stateCode: "UT",
    stateName: "Utah",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Utah Department of Health and Human Services sponsors Conrad 30 applications.",
    tips: "Utah has rural health needs in southern and eastern parts of the state. Rural communities outside Salt Lake City and Provo have the greatest need. Growing population creates increasing demand.",
    websiteUrl: "https://dhhs.utah.gov",
  },
  VT: {
    stateCode: "VT",
    stateName: "Vermont",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Vermont Department of Health sponsors applications.",
    tips: "Vermont has widespread rural health needs. The Northeast Kingdom and southern Vermont have the greatest shortages. Small state with limited applications — less competitive. Community health centers are common placements.",
    websiteUrl: "https://www.healthvermont.gov",
  },
  VA: {
    stateCode: "VA",
    stateName: "Virginia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Virginia Department of Health sponsors Conrad 30 applications.",
    tips: "Virginia has strong rural health needs in southwestern Appalachian Virginia and the Southside region. Northern Virginia is very competitive. Rural areas have better chances. The state has an established IMG community.",
    websiteUrl: "https://www.vdh.virginia.gov",
  },
  WA: {
    stateCode: "WA",
    stateName: "Washington",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Washington State Department of Health sponsors Conrad 30 applications.",
    tips: "Washington has rural health needs east of the Cascades. Eastern Washington and rural Olympic Peninsula have the greatest need. Seattle metro is very competitive. Behavioral health is a statewide priority.",
    websiteUrl: "https://doh.wa.gov",
  },
  WV: {
    stateCode: "WV",
    stateName: "West Virginia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. West Virginia Department of Health and Human Resources sponsors applications.",
    tips: "West Virginia has some of the highest physician shortage rates in the country. Nearly the entire state is designated HPSA. Fast processing times. Very IMG-friendly. Strong demand for primary care across all communities.",
    websiteUrl: "https://dhhr.wv.gov",
  },
  WI: {
    stateCode: "WI",
    stateName: "Wisconsin",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Wisconsin Department of Health Services sponsors Conrad 30 applications.",
    tips: "Wisconsin has rural health needs in northern and western regions. Marshfield Clinic system has historically been a major employer of IMG physicians. Community health centers and critical access hospitals are common placements.",
    websiteUrl: "https://www.dhs.wisconsin.gov",
  },
  WY: {
    stateCode: "WY",
    stateName: "Wyoming",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Frontier Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Wyoming Department of Health sponsors Conrad 30 applications.",
    tips: "Wyoming has the smallest population of any state but significant rural health needs. Nearly all communities are designated HPSAs. Very fast processing. Least competitive state for waivers. Expect rural lifestyle.",
    websiteUrl: "https://health.wyo.gov",
  },
};

export function getWaiverStateByCode(code: string): WaiverState | null {
  return WAIVER_STATES[code.toUpperCase()] || null;
}

export function getWaiverStateBySlug(slug: string): WaiverState | null {
  const entry = Object.values(WAIVER_STATES).find(
    (s) => s.stateName.toLowerCase().replace(/\s+/g, "-") === slug.toLowerCase()
  );
  return entry || null;
}

export function getAllWaiverStateSlugs(): { state: string }[] {
  return Object.values(WAIVER_STATES).map((s) => ({
    state: s.stateName.toLowerCase().replace(/\s+/g, "-"),
  }));
}
