export interface WaiverState {
  stateCode: string;
  stateName: string;
  conradSlots: number;
  flexSlots: number;
  timeline: string;
  processingTime: string;
  priorityAreas: string[];
  specialtyNeeds: string[];
  requirements: string;
  tips: string;
  websiteUrl: string;
  /** Data confidence: "official" = from state DOH/3RNET, "community" = from physician reports, "estimated" = based on available data */
  confidence?: "official" | "community" | "estimated";
  /** When was this state's data last verified */
  lastVerified?: string;
  /** Application window: when the state accepts Conrad 30 applications */
  applicationWindow?: string;
  /** State health department contact for J-1 waiver */
  contactInfo?: string;
}

export const WAIVER_STATES: Record<string, WaiverState> = {
  AL: {
    stateCode: "AL",
    stateName: "Alabama",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a federally designated HPSA or MUA for 3 years. Alabama Department of Public Health sponsors J-1 waiver applications through the Conrad 30 program.",
    tips: "Alabama typically has remaining Conrad slots. Eligible for DRA (western Black Belt counties) and SCRC waivers — two alternative unlimited-slot pathways. Rural Black Belt counties (Greene, Sumter, Wilcox, Hale) have among the highest physician shortages in the US. Mobile and Birmingham suburbs have some FQHC opportunities. UAB is the major academic system. No state income tax on first $6,000 for married filing jointly. Low cost of living statewide.",
    websiteUrl: "https://www.alabamapublichealth.gov",
  },
  AK: {
    stateCode: "AK",
    stateName: "Alaska",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must serve in a designated HPSA or MUA. Alaska Department of Health sponsors Conrad 30 applications. Tribal health facilities are common placement sites.",
    tips: "Alaska typically has 10-15 remaining Conrad slots — less competitive. Tribal and Indian Health Service facilities are common placements. Remote locations offer significantly higher compensation (often $50-100K+ above lower-48 rates). No state income tax. Extremely high cost of living especially in rural areas. Expect true frontier medicine — some communities are accessible only by plane. ANTHC (Alaska Native Tribal Health Consortium) is a major employer. Great option for adventurous physicians willing to embrace isolation.",
    websiteUrl: "https://health.alaska.gov",
  },
  AZ: {
    stateCode: "AZ",
    stateName: "Arizona",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-9 months",
    processingTime: "45-90 days",
    priorityAreas: ["Primary Care", "Behavioral Health", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Arizona ADHS administers the Conrad 30 program. Important: Arizona does NOT offer flex waiver slots — all 30 must be in designated shortage areas. Arizona fills all 30 slots annually. Preference given to primary care and behavioral health.",
    tips: "Arizona fills all 30 Conrad slots every year. Strong demand in Maricopa County suburbs and rural areas. Behavioral health specialists are especially needed. Consider SCRC (Southeast Crescent Regional Commission) or HHS Clinical Care Waiver as alternatives. Apply through ADHS as early as October 1.",
    websiteUrl: "https://www.azdhs.gov",
  },
  AR: {
    stateCode: "AR",
    stateName: "Arkansas",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Arkansas DOH reviews and sponsors applications. Arkansas fills all 30 Conrad slots annually (FY 2024). Also eligible for DRA (Delta Regional Authority) waivers — many eastern Arkansas counties are in the DRA footprint with unlimited slots. Full unrestricted AR medical license required.",
    tips: "Arkansas fills all 30 Conrad slots every year — apply early (October 1). The Delta region in eastern Arkansas (Phillips, Lee, St. Francis, Crittenden counties) has the highest HPSA scores and greatest need. DRA pathway is available for Delta counties — unlimited additional slots beyond Conrad. Western Arkansas (Fort Smith area) and northwest Arkansas (outside Fayetteville/Rogers) also have growing need. Arkansas has one of the lowest costs of living in the nation. State income tax is graduated (0-4.4%). UAMS (University of Arkansas for Medical Sciences) is the major academic center for networking.",
    websiteUrl: "https://www.healthy.arkansas.gov",
  },
  CA: {
    stateCode: "CA",
    stateName: "California",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-18 months (one of the longest in the nation)",
    processingTime: "90-180 days — HCAI reviews are thorough and slow",
    priorityAreas: ["Primary Care", "HPSA Focus", "Community Health Centers", "Federally Qualified Health Centers"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. California HCAI (Department of Health Care Access and Information) administers the program. Strong preference for FQHC placements. California requires employers to demonstrate inability to recruit a US physician for 6+ months. HPSA score of 14+ recommended for competitive applications. State requires full California medical license at time of application.",
    tips: "California is the most competitive Conrad 30 state — slots typically fill by January/February of each fiscal year (which starts October 1). FQHC and community health center placements have significantly better approval rates than private practice. Central Valley (Fresno, Bakersfield, Stockton) and rural Northern California (Redding, Eureka) have highest need and best chances. Inland Empire (San Bernardino, Riverside) is growing rapidly with physician shortages. Avoid applying for urban LA or SF Bay Area placements — extremely competitive and often denied. Apply as early as October 1 as possible. Budget for California's high cost of living when evaluating offers.",
    websiteUrl: "https://hcai.ca.gov",
    applicationWindow: "Opens October 1, closes October 31. Secondary cycle in December if slots remain. Fills within days — apply on Oct 1.",
  },
  CO: {
    stateCode: "CO",
    stateName: "Colorado",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Colorado CDPHE sponsors applications. Colorado typically has remaining slots (not among states that fill all 30). No alternative regional pathways. HHS is the only unlimited backup. Full unrestricted CO medical license required.",
    tips: "Colorado typically does not fill all 30 Conrad slots — you have a real chance even if applying after October. Eastern Plains (Burlington, Lamar, La Junta) and Western Slope (Montrose, Grand Junction rural, Durango) have the highest need. San Luis Valley (Alamosa) has critical shortages. Denver metro HPSA sites exist but are competitive. Behavioral health is a statewide crisis — psychiatrists are in extremely high demand. Colorado has a flat state income tax (4.4%). High quality of life but cost of living in Denver/Boulder is steep. University of Colorado is the major academic system.",
    websiteUrl: "https://cdphe.colorado.gov",
  },
  CT: {
    stateCode: "CT",
    stateName: "Connecticut",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Community Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Connecticut DPH administers the program. Connecticut fills all 30 Conrad slots annually (FY 2024). No alternative regional pathways available. Full unrestricted CT medical license required.",
    tips: "Connecticut fills all 30 Conrad slots every year. Urban underserved areas in Hartford, Bridgeport, New Haven, and Waterbury have the highest need and best chances. FQHCs like Community Health Center Inc. and Fair Haven Community Health are major waiver employers. Yale-affiliated community sites in New Haven are competitive but possible. Northeast and northwest rural CT have growing demand. Connecticut has a relatively high cost of living and state income tax (graduated 3-6.99%). Strong academic medical infrastructure (Yale, UConn Health).",
    websiteUrl: "https://portal.ct.gov/dph",
    applicationWindow: "Opens October 1 at 8:00 AM EST, closes October 15 at 4:30 PM EST. If 30+ applications, lottery conducted. Extended to April 1 only if fewer than 30 received.",
  },
  DE: {
    stateCode: "DE",
    stateName: "Delaware",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Delaware Division of Public Health sponsors Conrad 30 applications.",
    tips: "Delaware typically has 12+ remaining Conrad slots — low competition. Southern Delaware (Sussex County) has greatest need. Bayhealth and ChristianaCare are major employers. Small state with limited applicants — good backup option. No alternative regional pathways. Delaware has no sales tax and graduated income tax (up to 6.6%).",
    websiteUrl: "https://dhss.delaware.gov/dph",
  },
  FL: {
    stateCode: "FL",
    stateName: "Florida",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-15 months (competitive, plan early)",
    processingTime: "90-120 days — DOH review can be thorough for competitive applications",
    priorityAreas: ["Primary Care", "Rural Health", "HPSA", "Behavioral Health", "Geriatrics"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "Geriatrics"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Florida DOH administers the Conrad 30 program. Florida is highly competitive due to desirable lifestyle and large IMG population. HPSA score of 14+ strongly recommended. MAJOR ADVANTAGE: The entire state of Florida is covered by SCRC (Southeast Crescent Regional Commission) — every single county qualifies for SCRC waivers with UNLIMITED slots. This means even when Conrad 30 slots fill, SCRC provides an alternative ($3,000 fee applies).",
    tips: "Florida is very competitive for Conrad 30 — second only to California and New York in demand. No state income tax is a major draw. BUT here's the key insight most people miss: ALL of Florida is covered by SCRC waivers (launched 2022), which have unlimited slots. This means Florida effectively has more waiver capacity than almost any other state. The $3,000 SCRC fee is worth it when Conrad fills. Best areas: rural panhandle (Gadsden, Jackson, Bay), central agricultural areas (Polk, Highlands, Hardee), and northern tier (Marion, Putnam, Baker). South Florida (Miami-Dade, Broward) is competitive even for SCRC. Geriatrics is growing need due to aging population. Large IMG community statewide.",
    websiteUrl: "https://www.floridahealth.gov",
    applicationWindow: "Opens October 1 at 8:00 AM. Closes ~October 12 (~2-week window only). Prioritized by HPSA score, rural/primary care preference.",
  },
  GA: {
    stateCode: "GA",
    stateName: "Georgia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Georgia DCH sponsors Conrad 30 applications. Georgia fills all 30 Conrad slots every year (FY 2024 data). Also eligible for SCRC (Southeast Crescent Regional Commission) waivers — unlimited slots covering 428 counties across 7 southeastern states including Georgia. Full unrestricted GA medical license required.",
    tips: "Georgia fills all 30 Conrad slots annually — apply early (October 1). Southern and eastern Georgia have the highest HPSA scores and greatest need. Atlanta metro has limited HPSA sites and is very competitive. Savannah, Augusta, Macon, Albany, and Columbus have better chances. The SCRC pathway is a major advantage for Georgia — unlimited additional slots for eligible counties. Georgia has a growing IMG physician community. State income tax is graduated (1-5.49%). Consider Emory, MCG/Augusta University, and Mercer residency program connections for networking.",
    websiteUrl: "https://dch.georgia.gov",
  },
  HI: {
    stateCode: "HI",
    stateName: "Hawaii",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Islands", "Native Hawaiian Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Hawaii Department of Health sponsors applications. Neighbor islands have greatest need.",
    tips: "Hawaii typically has 10-18 remaining Conrad slots — low competition. Neighbor islands (Big Island, Maui, Kauai, Molokai) have the greatest need — Honolulu/Oahu is more competitive. Extremely high cost of living (highest in US), but some employers provide housing assistance. No alternative regional pathways. Unique practice environment with diverse patient population. Hawaii has a moderate state income tax (graduated up to 11%). If you can handle the cost of living, Hawaii offers desirable lifestyle with reliable waiver availability.",
    websiteUrl: "https://health.hawaii.gov",
  },
  ID: {
    stateCode: "ID",
    stateName: "Idaho",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Idaho Department of Health and Welfare sponsors applications.",
    tips: "Idaho typically has 14-16 remaining Conrad slots — good for late applicants. Boise metro has limited HPSA sites. Eastern Idaho (Idaho Falls, Pocatello), central Idaho (Sun Valley area), and northern Idaho (Coeur d'Alene area rural) have greatest need. No alternative regional pathways. Idaho has a graduated state income tax (1-5.8%). Growing state with increasing physician demand. Low cost of living outside Boise. Family-friendly communities.",
    websiteUrl: "https://healthandwelfare.idaho.gov",
  },
  IL: {
    stateCode: "IL",
    stateName: "Illinois",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months (moderate competitiveness)",
    processingTime: "60-90 days — IDPH is reasonably efficient",
    priorityAreas: ["Primary Care", "Rural Health", "Urban Underserved", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Illinois DPH (Department of Public Health) administers the Conrad 30 program. HPSA score of 10+ recommended. Illinois has a large residency training infrastructure — many waiver physicians trained in-state. Full Illinois medical license required. The state also accepts applications through HHS Clinical Care Waivers (unlimited slots, HPSA score 7+ required) for eligible sites.",
    tips: "Illinois offers a mix of urban and rural waiver opportunities. Downstate Illinois (Peoria, Springfield, Champaign-Urbana, Carbondale, Rockford) is significantly less competitive than Chicago. Chicago's south side and west side FQHCs have strong track records for waiver placements. Cook County Health System has historically been a major waiver employer. East St. Louis has critical needs. Large IMG physician community — network through Illinois State Medical Society IMG section. Consider that Illinois has a relatively high state income tax (4.95% flat rate).",
    websiteUrl: "https://dph.illinois.gov",
    applicationWindow: "Three phases: Phase 1 Oct 1-31, Phase 2 Jan 1-31 (if slots remain), Phase 3 Apr 1-30 (if still remaining). Email to DPH.J1Waiver@illinois.gov.",
  },
  IN: {
    stateCode: "IN",
    stateName: "Indiana",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Indiana ISDH administers the program. Important: Indiana does NOT offer flex waiver slots. Indiana fills all 30 slots annually.",
    tips: "Indiana fills all 30 Conrad slots every year and does not support flex waivers. Southern Indiana and rural counties have highest demand. Community health centers are common placements. Consider ARC waiver for eligible Appalachian southern Indiana counties as an alternative pathway.",
    websiteUrl: "https://www.in.gov/health",
  },
  IA: {
    stateCode: "IA",
    stateName: "Iowa",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Iowa Department of Public Health sponsors Conrad 30 applications.",
    tips: "Iowa typically has 10 remaining Conrad slots — moderate competition. Most counties outside Des Moines and Iowa City metro qualify as HPSA. Western and southern Iowa have highest need. No alternative regional pathways. Iowa has a graduated state income tax (0.33-6%). Low cost of living, family-friendly communities. University of Iowa is the major academic system. Des Moines University and Broadlawns Medical Center are IMG-friendly employers.",
    websiteUrl: "https://hhs.iowa.gov",
  },
  KS: {
    stateCode: "KS",
    stateName: "Kansas",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Kansas Department of Health and Environment administers the program.",
    tips: "Kansas fills all 30 Conrad slots annually (FY 2024). Western Kansas has critical shortages — Dodge City, Garden City, Liberal. No alternative regional pathways. Kansas has a graduated state income tax (3.1-5.7%). KU Medical Center is the major academic system. Wichita has some FQHC opportunities. Via Christi and Ascension are key employers.",
    websiteUrl: "https://www.kdhe.ks.gov",
    applicationWindow: "Phase 1: September 1 - November 30 (decisions by December 15). Phase 2: after November 30 only if slots remain. Kansas opens BEFORE October 1.",
  },
  KY: {
    stateCode: "KY",
    stateName: "Kentucky",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Kentucky CHFS sponsors applications. Kentucky has filled every single Conrad 30 slot every year for 20+ years — one of only 3 states (with Michigan and New York) with a perfect fill record. Also eligible for both ARC (Appalachian) and DRA (Delta) waivers — giving Kentucky access to more unlimited-slot pathways than almost any other state.",
    tips: "Kentucky fills all 30 Conrad slots every single year — has never had an unused slot in 20+ years of data (3RNET). Apply on October 1 or earlier if possible. Eastern Appalachian Kentucky has the highest HPSA scores and greatest need. Kentucky has a unique advantage: eligible for BOTH ARC and DRA unlimited-slot waiver pathways, covering much of the state. This means even when Conrad is full, alternatives exist. Louisville and Lexington suburbs have some HPSA sites but are competitive. Rural communities in Pike, Floyd, Harlan, and Clay counties have critical needs. No state income tax on first $10,000 (graduated 0-4.5%). Strong IMG community at University of Kentucky and University of Louisville residency programs.",
    websiteUrl: "https://chfs.ky.gov",
    applicationWindow: "Opens October 1, initial deadline October 31. Extended until July 30 if waivers remain. Fills every year — apply October 1.",
  },
  LA: {
    stateCode: "LA",
    stateName: "Louisiana",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Louisiana DOH sponsors Conrad 30 applications. Louisiana fills all 30 Conrad slots annually (FY 2024). Also eligible for DRA (Delta Regional Authority) waivers with unlimited slots — much of Louisiana is in the DRA footprint. Full unrestricted LA medical license required.",
    tips: "Louisiana fills all 30 Conrad slots every year. Northern Louisiana parishes (Ouachita, Morehouse, Richland) and rural Acadiana have highest HPSA scores. The DRA pathway is a major alternative — many Louisiana parishes qualify for unlimited DRA slots. Baton Rouge and New Orleans suburbs have limited HPSA sites. Louisiana has a long history of supporting IMG physicians, particularly in rural hospitals. State income tax is graduated (1.85-4.25%). Consider LSU Health and Tulane residency connections for networking.",
    websiteUrl: "https://ldh.la.gov",
    applicationWindow: "Primary care: October 1. Specialists: December 1. First round deadline: December 31. Second round: January 1 (if slots remain). Final: July 31. Preference for in-state residency graduates.",
  },
  ME: {
    stateCode: "ME",
    stateName: "Maine",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Maine Department of Health and Human Services sponsors applications.",
    tips: "Maine fills all 30 Conrad slots annually (FY 2024). Northern (Aroostook County) and western Maine have highest need. Aging population drives primary care demand. No alternative regional pathways. Maine has a graduated state income tax (5.8-7.15%). MaineHealth and Northern Light Health are major employer systems. Portland area is competitive but rural Maine has critical shortages.",
    websiteUrl: "https://www.maine.gov/dhhs",
  },
  MD: {
    stateCode: "MD",
    stateName: "Maryland",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Maryland DOH administers the Conrad 30 program. Maryland typically has remaining slots. Western Maryland counties are ARC-eligible (unlimited alternative pathway). Full unrestricted MD medical license required.",
    tips: "Maryland typically has remaining Conrad slots — moderate competition. Baltimore has major FQHC networks with established waiver relationships. Western Maryland (Allegany, Garrett counties) qualifies for ARC waivers with unlimited slots. Eastern Shore has growing rural need. Suburban MD near DC has very few HPSA sites. Strong academic infrastructure: Johns Hopkins, University of Maryland, Uniformed Services University. Maryland has relatively high state income tax (graduated 2-5.75% plus county surcharges). H-1B cap-exempt employers include Hopkins, UMD Medical System, NIH.",
    websiteUrl: "https://health.maryland.gov",
  },
  MA: {
    stateCode: "MA",
    stateName: "Massachusetts",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "8-15 months (competitive academic state)",
    processingTime: "90-120 days — MA DPH is thorough",
    priorityAreas: ["Primary Care", "Community Health Centers", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. MA DPH sponsors applications. Massachusetts fills all 30 Conrad slots annually (FY 2024). Highly competitive due to concentration of medical institutions and desirable quality of life. HPSA score of 14+ recommended. Full unrestricted MA medical license required.",
    tips: "Massachusetts fills all 30 slots every year — very competitive. FQHCs in Springfield, Worcester, Brockton, Fall River, New Bedford, and Lowell have the best approval rates. Boston proper is extremely competitive — South Boston and Dorchester FQHCs are possible but limited. Western Massachusetts (Berkshires, Pioneer Valley) has growing rural need. MA has the strongest H-1B cap-exempt employer base in the country (Mass General, Brigham, Beth Israel, BMC, UMass). High cost of living and state income tax (5% flat + 4% surtax on income over $1M). The academic medical community is unparalleled for networking and career development.",
    websiteUrl: "https://www.mass.gov/dph",
    applicationWindow: "Opens October 1, closes January 15. Second round if all 30 not filled. Applications via REDCap system.",
  },
  MI: {
    stateCode: "MI",
    stateName: "Michigan",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-10 months (efficient, IMG-friendly process)",
    processingTime: "45-75 days — MDHHS is responsive and organized",
    priorityAreas: ["Primary Care", "Underserved Areas", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Michigan DHHS sponsors Conrad 30 applications. HPSA score of 7+ typically sufficient. Michigan has one of the most IMG-friendly medical licensing processes in the nation. Full Michigan medical license required. Michigan also participates in HHS Clinical Care Waivers (unlimited slots, HPSA score 7+ required) for eligible sites.",
    tips: "Michigan fills all 30 Conrad slots every single year — one of only 3 states (with Kentucky and New York) that has never had unused slots in 20+ years of data. Despite high competition, Michigan remains a top-5 state for IMG physicians. Detroit has massive physician shortages — Beaumont, Henry Ford, DMC/Tenet systems are major waiver employers. Flint and Saginaw have critical needs. Upper Peninsula is severely underserved with high HPSA scores. Also consider HHS Clinical Care Waiver (unlimited slots) or ARC waiver for eligible counties as alternatives when Conrad slots fill. Michigan has a strong H-1B cap-exempt hospital base (University of Michigan, Beaumont, Henry Ford, Spectrum Health). State income tax is flat 4.25%.",
    websiteUrl: "https://www.michigan.gov/mdhhs",
    applicationWindow: "Opens September 1, closes November 1 at 5:00 PM. Strict 2-month window. Applications must be RECEIVED (not postmarked) by deadline. Opens before federal fiscal year.",
  },
  MN: {
    stateCode: "MN",
    stateName: "Minnesota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Minnesota DOH sponsors applications. Minnesota fills all 30 Conrad slots annually (FY 2024). No alternative regional pathways (not in ARC, DRA, or SCRC regions). HHS Clinical Care Waiver is the only backup for primary care/psychiatry. Full unrestricted MN medical license required.",
    tips: "Minnesota fills all 30 Conrad slots every year — apply on October 1. No alternative regional pathways available (MN is not in ARC, DRA, or SCRC). HHS Clinical Care Waiver is the only unlimited-slot alternative for primary care/psychiatry. Southern and western Minnesota (Marshall, Worthington, Mankato area) have highest need. Iron Range (Duluth, Hibbing, Virginia) has growing demand. Twin Cities metro has very limited HPSA sites. Mayo Clinic system and HealthPartners are major employers. Minnesota has relatively high state income tax (graduated, up to 9.85%). Excellent quality of life and school systems. Consider that winter weather is a real factor — it can affect recruitment and retention.",
    websiteUrl: "https://www.health.state.mn.us",
  },
  MS: {
    stateCode: "MS",
    stateName: "Mississippi",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Delta Region", "Maternal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "OB/GYN", "Psychiatry", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Mississippi MSDH sponsors Conrad 30 applications. Mississippi typically has remaining slots. Major advantage: eligible for THREE alternative pathways — DRA (Delta), SCRC (southeast), and ARC (northeast hill counties). Among the most waiver-friendly states in the nation.",
    tips: "Mississippi has among the highest physician shortage rates in the nation and typically does not fill all 30 Conrad slots. The Delta (Sunflower, Bolivar, Washington, Leflore counties) has some of the highest HPSA scores in the country. THREE alternative unlimited-slot pathways available: DRA covers the Delta and western MS, SCRC covers southeastern MS, and ARC covers northeastern hill counties. This gives Mississippi more waiver capacity per capita than almost any state. Lowest cost of living in the US. No state income tax on first $5,000 (graduated up to 5%). UMMC (University of Mississippi Medical Center) is the major academic system. Maternal health is a critical priority — OB/GYNs are desperately needed.",
    websiteUrl: "https://msdh.ms.gov",
  },
  MO: {
    stateCode: "MO",
    stateName: "Missouri",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Missouri DHSS sponsors applications. Missouri fills all 30 Conrad slots annually and does NOT support flex waivers (0 flex usage reported). Also eligible for DRA waivers for qualifying Bootheel-region counties. Full unrestricted MO medical license required.",
    tips: "Missouri fills all 30 Conrad slots every year and has zero flex slot usage. Ozarks and southeast Bootheel region have highest HPSA scores and greatest need. DRA pathway available for Bootheel counties (unlimited slots). Kansas City and St. Louis metro have limited HPSA-designated community health centers. Rural western and south-central Missouri has growing demand. Missouri has a flat 4.8% state income tax.",
    websiteUrl: "https://health.mo.gov",
    applicationWindow: "Opens October 1, closes October 31 — very short 1-month window. Site approval required from MO DHSS. Reviewed within 20 days.",
  },
  MT: {
    stateCode: "MT",
    stateName: "Montana",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Frontier Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Montana Department of Public Health and Human Services sponsors applications.",
    tips: "Montana typically has 14+ remaining Conrad slots — low competition. Most communities outside Billings and Missoula are HPSA-designated. Indian Health Service and tribal facilities are common placements. No state income tax on first $18,150 (graduated up to 5.9%). Frontier medicine with very low population density. No alternative regional pathways. Excellent quality of life for outdoor enthusiasts. Billings Clinic and Providence Health are major employer systems.",
    websiteUrl: "https://dphhs.mt.gov",
  },
  NE: {
    stateCode: "NE",
    stateName: "Nebraska",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Nebraska Department of Health and Human Services sponsors Conrad 30 applications.",
    tips: "Nebraska typically has 10 remaining Conrad slots. Western and central Nebraska (Panhandle, Sandhills) have highest need. Omaha and Lincoln metro are competitive. No alternative regional pathways. Nebraska has a graduated state income tax (2.46-5.84%). Low cost of living in rural areas. UNMC (University of Nebraska Medical Center) is the major academic system. CHI Health and Bryan Health are key employers.",
    websiteUrl: "https://dhhs.ne.gov",
  },
  NV: {
    stateCode: "NV",
    stateName: "Nevada",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Nevada Division of Public and Behavioral Health sponsors applications.",
    tips: "Nevada typically has 12 remaining Conrad slots. Rural Nevada (Elko, Ely, Winnemucca, Pahrump) has critical needs. Las Vegas and Reno have some HPSA-designated FQHCs. No state income tax — major financial advantage. No alternative regional pathways. Rapidly growing population driving physician demand. UNLV School of Medicine (opened 2017) is expanding the academic footprint. Touro University and UNR also train physicians.",
    websiteUrl: "https://dpbh.nv.gov",
  },
  NH: {
    stateCode: "NH",
    stateName: "New Hampshire",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. New Hampshire Department of Health and Human Services sponsors applications.",
    tips: "New Hampshire typically has 14 remaining Conrad slots — low competition. Northern NH (Berlin, Coos County, North Country) has greatest need. No state income tax on earned income (5% on dividends/interest only). No alternative regional pathways. Dartmouth-Hitchcock is the major academic employer. Community health centers throughout the state. High quality of life in New England setting.",
    websiteUrl: "https://www.dhhs.nh.gov",
  },
  NJ: {
    stateCode: "NJ",
    stateName: "New Jersey",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "8-15 months (competitive, similar to NY process)",
    processingTime: "90-120 days — NJ DOH is thorough but not fast",
    priorityAreas: ["Primary Care", "Urban Underserved", "Community Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. NJ DOH sponsors Conrad 30 applications. Competitive due to desirable location (NYC metro proximity) and large IMG population. HPSA score of 12+ recommended for competitive applications. Full unrestricted NJ medical license required. Employer must demonstrate inability to recruit US physicians.",
    tips: "New Jersey is moderately to highly competitive — proximity to NYC makes it desirable. Best chances are in urban underserved areas: Newark, Camden, Trenton, Paterson, Elizabeth, and Atlantic City. FQHCs in these cities have strong approval track records. South Jersey rural areas have growing need. NJ has no flex slots beyond Conrad 30 — so exactly 30 slots per year. Large and well-organized IMG community — NJ Medical Society has IMG-specific resources. NJ has a graduated state income tax (1.4-10.75%) — high earners pay more. Consider NJ as a backup to NY — similar geography, somewhat less competitive process.",
    websiteUrl: "https://www.nj.gov/health",
  },
  NM: {
    stateCode: "NM",
    stateName: "New Mexico",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Emergency Medicine"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. New Mexico Department of Health sponsors applications. Tribal health facilities are common placements.",
    tips: "New Mexico fills all 30 Conrad slots annually (FY 2024). Critical physician shortages statewide. Indian Health Service and tribal facilities (Navajo Nation, Pueblo communities) are major employers. UNM Health Sciences Center is the dominant academic system. Santa Fe and Albuquerque suburbs have some FQHC sites. Southern NM (Las Cruces, Roswell) has growing need. No alternative regional pathways. New Mexico has a graduated state income tax (1.7-5.9%). Very IMG-friendly state with established support networks.",
    websiteUrl: "https://www.nmhealth.org",
  },
  NY: {
    stateCode: "NY",
    stateName: "New York",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "12-24 months (longest in nation — plan accordingly)",
    processingTime: "120-180+ days — NYS DOH is notoriously slow; some cases take 6+ months for state processing alone before federal DOS submission",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. NYS Department of Health administers the program. Extremely competitive — all 30 slots plus flex slots typically fill within weeks of October 1. Employers must demonstrate active recruitment of US physicians for 6+ months. HPSA score matters — higher scores get priority. Full unrestricted NY medical license required at time of Conrad 30 application. New York also accepts applications through USDA and HHS waiver pathways as alternatives.",
    tips: "New York is the most competitive waiver state. Slots fill within the first 2-3 weeks of the federal fiscal year (October 1). If you miss the window, you wait an entire year. Upstate New York (Buffalo, Syracuse, Albany, Adirondack region) has significantly better chances than NYC metro. NYC boroughs (Bronx, Brooklyn) are possible through FQHCs but extremely competitive. Consider USDA or HHS waiver pathways as alternatives to Conrad 30. Always have 2-3 backup states ready. Start your employer search 12+ months before your J-1 waiver deadline. Budget $5,000-15,000 for immigration attorney fees in NY (complex state process).",
    websiteUrl: "https://www.health.ny.gov",
    applicationWindow: "Opens ~September/October. NOT first-come-first-served — NY collects all applications by deadline (~January), then ranks and selects top 30 based on HPSA scores and community need.",
  },
  NC: {
    stateCode: "NC",
    stateName: "North Carolina",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months (moderate, growing demand)",
    processingTime: "60-90 days — NC DHHS is reasonably efficient",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health", "Maternal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. NC DHHS sponsors applications. HPSA score of 7+ typically sufficient. Full unrestricted NC medical license required. NC also participates in ARC (Appalachian Regional Commission) waivers for eligible western mountain counties. SCRC (Southeast Crescent Regional Commission) waivers available for eligible eastern counties.",
    tips: "North Carolina is a growing state with increasing physician demand. Eastern NC (Greenville, Rocky Mount, Wilson, Lumberton) has critical rural health needs and the highest HPSA scores. Western mountain communities (Asheville area, Appalachian counties) qualify for ARC waivers — giving additional slots beyond Conrad 30. Charlotte and Raleigh-Durham suburbs have growing HPSA-designated sites but are more competitive. NC has a large residency training infrastructure (Duke, UNC, Wake Forest, ECU) — many graduates stay in-state. Reasonable cost of living. State income tax is flat 4.5% (recently reduced). Growing IMG community statewide. Community health centers in eastern NC and mountain communities have best approval rates.",
    websiteUrl: "https://www.ncdhhs.gov",
  },
  ND: {
    stateCode: "ND",
    stateName: "North Dakota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. North Dakota Department of Health sponsors Conrad 30 applications.",
    tips: "North Dakota typically has 16 remaining Conrad slots — very low competition. Most communities outside Fargo and Bismarck qualify. Western ND oil country (Williston, Dickinson) has growing populations and demand. Fast processing. No alternative regional pathways. ND has a graduated state income tax (0-1.95% — among lowest in nation). Sanford Health and CHI St. Alexius are major employers. Extreme winters but strong community support.",
    websiteUrl: "https://www.health.nd.gov",
  },
  OH: {
    stateCode: "OH",
    stateName: "Ohio",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-10 months (one of the most IMG-friendly processes)",
    processingTime: "45-75 days — ODH is responsive and well-organized",
    priorityAreas: ["Primary Care", "Urban Underserved", "Rural Health", "Behavioral Health", "Appalachian Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Ohio Department of Health (ODH) administers the Conrad 30 program. Ohio is widely considered one of the most IMG-friendly states in the nation. HPSA score of 7+ typically sufficient. Ohio also participates in ARC (Appalachian Regional Commission) waivers for eligible Appalachian counties — this provides additional slots beyond Conrad 30. Full unrestricted Ohio medical license required.",
    tips: "Ohio is a top-tier choice for J-1 waiver physicians. Reasonable cost of living, no extreme weather by physician standards, and a massive IMG physician community. Appalachian counties in southeast Ohio (Athens, Vinton, Meigs, Gallia) have critical needs and highest HPSA scores. Cleveland metro has multiple FQHC placements. Dayton, Youngstown, and Toledo have strong hospital-based waiver positions. Columbus suburbs are growing with new HPSA designations. ARC waiver pathway gives Ohio effectively more than 30 total slots. The Ohio State Medical Association has an active IMG section. Ohio has a moderate state income tax (0-3.75% graduated). Strong H-1B cap-exempt employer base (Cleveland Clinic, Ohio State, UC Health, MetroHealth).",
    websiteUrl: "https://odh.ohio.gov",
    applicationWindow: "Opens October 1 (rolling, first-come-first-served). Primary care deadline: January 31. FLEX/sub-specialist window: January 1 - May 31. Review: primary care 45 days, others 90 days. $3,571 fee.",
  },
  OK: {
    stateCode: "OK",
    stateName: "Oklahoma",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Oklahoma State Department of Health sponsors Conrad 30 applications.",
    tips: "Oklahoma typically has 8 remaining Conrad slots. Western and southeastern OK have greatest need. Tribal health facilities (Cherokee Nation, Chickasaw Nation, Indian Health Service) are major employers. No alternative regional pathways. Oklahoma has a graduated state income tax (0.25-4.75%). Low cost of living. OU Health Sciences Center and OSU College of Osteopathic Medicine are the major academic systems.",
    websiteUrl: "https://oklahoma.gov/health",
  },
  OR: {
    stateCode: "OR",
    stateName: "Oregon",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine", "OB/GYN"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Oregon Health Authority (OHA) sponsors Conrad 30 applications. Oregon fills all 30 Conrad slots annually (FY 2024). No alternative regional pathways (not in ARC, DRA, or SCRC). HHS Clinical Care Waiver is the only backup. Full unrestricted OR medical license required.",
    tips: "Oregon fills all 30 Conrad slots every year — apply early. No ARC/DRA/SCRC alternative pathways available for Oregon. Eastern Oregon (Bend, Pendleton, La Grande, Klamath Falls, Burns) has critical shortages and highest HPSA scores. Southern Oregon (Medford, Grants Pass) also needs primary care. Portland metro has very limited HPSA sites and is extremely competitive. Oregon has no sales tax but has state income tax (graduated up to 9.9%). OHSU (Oregon Health & Science University) is the major academic system. Behavioral health is a statewide priority — psychiatrists are in particularly high demand.",
    websiteUrl: "https://www.oregon.gov/oha",
    applicationWindow: "Opens October 1, first-come-first-served. Fills very fast — 27 of 30 slots claimed by December 18, 2025 for FY2026. $2,000 application fee. Already reserving FY2027 slots.",
  },
  PA: {
    stateCode: "PA",
    stateName: "Pennsylvania",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months (moderate competitiveness)",
    processingTime: "60-90 days — PA DOH is reasonably efficient",
    priorityAreas: ["Primary Care", "Rural Health", "Urban Underserved", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. PA DOH administers the Conrad 30 program. HPSA score of 7+ typically sufficient. Full unrestricted PA medical license required. Pennsylvania also participates in ARC waivers for eligible Appalachian counties (covers much of central and western PA). HHS Clinical Care Waivers (unlimited slots) available for qualifying sites with HPSA score 7+.",
    tips: "Pennsylvania offers a strong mix of urban and rural waiver opportunities. Philadelphia has major FQHC networks with established waiver relationships (Philadelphia Health Centers, Project HOME). Pittsburgh's underserved neighborhoods have strong need. North-central PA (Williamsport, Lock Haven, Sunbury) and coal country (Scranton, Wilkes-Barre) are severely underserved with high HPSA scores. ARC waiver pathway is a significant advantage — many PA counties qualify, giving effectively more than 30 slots. PA has massive medical training infrastructure (Penn, Jefferson, Temple, Drexel, Pittsburgh, Geisinger). Large IMG community — PA Medical Society supports IMG integration. State income tax is flat 3.07% (one of the lowest with income tax). Cost of living is very reasonable outside Philadelphia.",
    websiteUrl: "https://www.health.pa.gov",
    applicationWindow: "Three phases: Phase 1 Oct 1 - Dec 15, Phase 2 Jan 1 - Jun 15, Phase 3 Jul 1 - Sep 15. FLEX slots only in second half of fiscal year. NOTE: PA requires 5-year service commitment (vs standard 3 years).",
  },
  RI: {
    stateCode: "RI",
    stateName: "Rhode Island",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Community Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Rhode Island Department of Health sponsors applications.",
    tips: "Rhode Island typically has 18 remaining Conrad slots — very low competition (smallest state). Providence and surrounding communities (Pawtucket, Central Falls, Woonsocket) have HPSA-designated FQHCs. No alternative regional pathways. Rhode Island has a graduated state income tax (3.75-5.99%). Brown University/Lifespan and Care New England are the major employer systems. Good backup option if neighboring MA and CT are full.",
    websiteUrl: "https://health.ri.gov",
  },
  SC: {
    stateCode: "SC",
    stateName: "South Carolina",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "MUA/MUP", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. SC DHEC sponsors applications. South Carolina fills all 30 Conrad slots annually (FY 2024). Major advantage: SC is eligible for BOTH ARC (Appalachian upstate counties) AND SCRC waivers — giving effectively three waiver pathways with unlimited additional capacity. Full unrestricted SC medical license required.",
    tips: "South Carolina fills all 30 Conrad slots every year, but you have excellent alternatives. Upstate SC (Anderson, Pickens, Oconee, Cherokee) qualifies for ARC waivers (unlimited, no fee). Much of SC is covered by SCRC waivers (unlimited, $3,000 fee). This means SC effectively has more waiver capacity than most states despite filling Conrad. Pee Dee region (Florence, Marion, Darlington) and Lowcountry rural areas have highest HPSA scores. MUSC (Charleston) and USC (Columbia) residency connections help with networking. No state income tax on first $3,460 (graduated 0-6.4%). Moderate cost of living.",
    websiteUrl: "https://scdhec.gov",
    applicationWindow: "Slot reservation begins JULY 1 (earliest of any state) for next fiscal year. First-come-first-served. Must reserve slot before submitting full application. Contact neelyk@dph.sc.gov.",
  },
  SD: {
    stateCode: "SD",
    stateName: "South Dakota",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "45-60 days",
    priorityAreas: ["Primary Care", "Rural Health", "Tribal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. South Dakota Department of Health sponsors Conrad 30 applications.",
    tips: "South Dakota typically has 14 remaining Conrad slots — low competition. Indian Health Service facilities on reservations (Pine Ridge, Rosebud) offer unique opportunities. No state income tax — major financial advantage. Fast processing. No alternative regional pathways. Sanford Health and Avera Health are major employers. Sioux Falls is the only metro area. Very low cost of living.",
    websiteUrl: "https://doh.sd.gov",
  },
  TN: {
    stateCode: "TN",
    stateName: "Tennessee",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "OB/GYN", "General Surgery"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Tennessee DOH sponsors Conrad 30 applications. Tennessee is eligible for BOTH ARC (Appalachian, eastern TN) AND DRA (Delta, western TN) waivers — giving the state access to unlimited additional slots through two separate regional pathways. Full unrestricted TN medical license required.",
    tips: "Tennessee has a unique advantage: eligible for both ARC and DRA unlimited-slot pathways in addition to Conrad 30. East Tennessee (Appalachian counties — Johnson, Scott, Morgan, Campbell) qualifies for ARC. West Tennessee (Shelby/Memphis metro excluded, but rural counties like Haywood, Lauderdale, Tipton) qualifies for DRA. Nashville suburbs have limited HPSA sites. Chattanooga, Knoxville suburbs, and rural middle TN have growing need. No state income tax on earned income (Hall income tax on interest/dividends was fully phased out in 2021). Tennessee has an active Vanderbilt, UT Health, and Meharry residency pipeline for networking.",
    websiteUrl: "https://www.tn.gov/health",
  },
  TX: {
    stateCode: "TX",
    stateName: "Texas",
    conradSlots: 30,
    flexSlots: 0,
    timeline: "6-10 months (faster than most large states)",
    processingTime: "45-75 days — DSHS is one of the more efficient state agencies",
    priorityAreas: ["Primary Care", "Rural Health", "Border Health", "Behavioral Health", "Maternal Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN", "General Surgery"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Texas DSHS (Department of State Health Services) administers the Conrad 30 program. Important: Texas does NOT offer flex waiver slots — all 30 must be in designated shortage areas. No state income tax. Employer must be in a HPSA or MUA. Texas accepts specialists beyond primary care more readily than most states. Full unrestricted Texas medical license required.",
    tips: "Texas is widely considered one of the best states for J-1 waivers despite having no flex slots. All 30 slots fill very quickly — often within the first days of the fiscal year (October 1). No state income tax makes Texas financially attractive. Rio Grande Valley, West Texas (El Paso, Lubbock, Midland-Odessa), and East Texas (Tyler, Longview, Texarkana) have the highest HPSA scores and need. Dallas-Fort Worth and Houston suburbs have growing HPSA-designated sites. Also consider HHS Clinical Care Waiver (unlimited slots, requires HPSA score 7+) as alternative to Conrad 30. Texas has one of the largest IMG physician communities in the US. Start employer search 8-10 months before your waiver deadline.",
    websiteUrl: "https://www.dshs.texas.gov",
    applicationWindow: "Opens ~October 1. Slots exhaust within first day/days. Submit via email to Conrad30@dshs.texas.gov. $3,000 application fee.",
  },
  UT: {
    stateCode: "UT",
    stateName: "Utah",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Utah Department of Health and Human Services sponsors Conrad 30 applications.",
    tips: "Utah typically has 12 remaining Conrad slots. Southern and eastern Utah (St. George rural areas, Moab, Price, Vernal) have greatest need. SLC and Provo metro are competitive. No alternative regional pathways. Utah has a flat state income tax (4.65%). Rapidly growing population driving physician demand. Intermountain Healthcare is the dominant employer system. University of Utah Health is the major academic center. Family-friendly state with excellent outdoor recreation.",
    websiteUrl: "https://dhhs.utah.gov",
  },
  VT: {
    stateCode: "VT",
    stateName: "Vermont",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Vermont DOH sponsors applications. Vermont typically has 10-20 remaining slots — one of the least competitive states. Notable: 78% of Vermont's Conrad placements are flex waivers (highest flex usage nationally). Full unrestricted VT medical license required.",
    tips: "Vermont is one of the best states for late applicants — typically has 10-20 remaining Conrad slots. The state has the highest flex waiver usage nationally (78% of placements). Northeast Kingdom and southern Vermont have the greatest shortages. Entire state is rural by most standards. Community health centers like Bi-State Primary Care and Federally Qualified Health Centers are the primary waiver employers. Vermont has a progressive income tax (graduated up to 8.75%) and high cost of living relative to salaries. UVM Medical Center is the major employer. Excellent quality of life if you enjoy rural New England.",
    websiteUrl: "https://www.healthvermont.gov",
  },
  VA: {
    stateCode: "VA",
    stateName: "Virginia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "Pediatrics", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Virginia DOH sponsors Conrad 30 applications. Virginia typically has some remaining slots. Eligible for both ARC (southwest Appalachian counties) and SCRC waivers — two alternative unlimited-slot pathways. Full unrestricted VA medical license required.",
    tips: "Virginia typically has remaining Conrad slots (not among the 19 states that fill all 30). Southwest Appalachian Virginia (Lee, Scott, Wise, Dickenson, Buchanan counties) has the highest HPSA scores and qualifies for ARC waivers. The Southside region (Danville, Martinsville) and Eastern Shore also have strong need. Parts of Virginia qualify for SCRC waivers too. Northern Virginia (NoVA) is extremely competitive — avoid for waiver purposes. Richmond and Hampton Roads have some FQHC opportunities. Virginia has a moderate state income tax (graduated 2-5.75%). Strong academic systems: UVA, VCU, EVMS for networking.",
    websiteUrl: "https://www.vdh.virginia.gov",
  },
  WA: {
    stateCode: "WA",
    stateName: "Washington",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health", "Behavioral Health"],
    specialtyNeeds: ["Family Medicine", "Psychiatry", "Internal Medicine", "Pediatrics"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Washington DOH sponsors Conrad 30 applications. Washington typically has some remaining slots. No alternative regional pathways (not in ARC, DRA, or SCRC). HHS Clinical Care Waiver is the only backup for primary care/psychiatry. Full unrestricted WA medical license required.",
    tips: "Washington typically has remaining Conrad slots — not as competitive as neighboring Oregon which fills all 30. No state income tax — major financial advantage alongside no alternative regional pathways. Eastern Washington (Yakima, Wenatchee, Spokane rural areas, Tri-Cities) and rural Olympic Peninsula have greatest need. Seattle metro has very few HPSA sites and is extremely competitive. Behavioral health is a statewide crisis — psychiatrists are in extremely high demand. University of Washington and its WWAMI network are the dominant academic system. High cost of living in Seattle metro but reasonable in eastern WA.",
    websiteUrl: "https://doh.wa.gov",
  },
  WV: {
    stateCode: "WV",
    stateName: "West Virginia",
    conradSlots: 30,
    flexSlots: 10,
    timeline: "6-10 months (fast processing, IMG-friendly)",
    processingTime: "45-60 days — one of the fastest state agencies",
    priorityAreas: ["Primary Care", "Rural Health", "Appalachian Region", "Behavioral Health", "Substance Abuse"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry", "General Surgery", "OB/GYN"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. WV DHHR sponsors applications. ALL of West Virginia is in the ARC (Appalachian Regional Commission) region — the entire state qualifies for ARC waivers with unlimited slots and no application fee. This is the biggest advantage any state has: Conrad 30 + unlimited ARC = essentially unlimited waiver capacity. Fast processing times.",
    tips: "West Virginia is arguably the best-positioned state for J-1 waivers because the ENTIRE state is ARC-eligible. This means even when Conrad 30 fills, ARC provides unlimited additional capacity at no cost. Nearly every community in WV is HPSA-designated — physician shortage rates are among the highest in the nation. Processing is fast (45-60 days at state level). Very IMG-friendly. WVU and Marshall University residency programs produce many IMG graduates who stay for waivers. Substance abuse and behavioral health are critical priorities. No state income tax on first $10,000 (graduated up to 6.5%). Low cost of living statewide. Strong demand for virtually every specialty.",
    websiteUrl: "https://dhhr.wv.gov",
  },
  WI: {
    stateCode: "WI",
    stateName: "Wisconsin",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-12 months",
    processingTime: "60-90 days",
    priorityAreas: ["Primary Care", "Rural Health"],
    specialtyNeeds: ["Family Medicine", "Internal Medicine", "Psychiatry"],
    requirements:
      "Must serve in a HPSA or MUA for 3 years. Wisconsin Department of Health Services sponsors Conrad 30 applications.",
    tips: "Wisconsin typically has 8 remaining Conrad slots. Northern and western Wisconsin have highest need. Marshfield Clinic system has historically been one of the largest waiver employers for IMG physicians in the nation. No alternative regional pathways. Wisconsin has a graduated state income tax (3.54-7.65%). MCW (Medical College of Wisconsin) and UW-Madison are the major academic systems. Gundersen Health and Prevea Health are also key employers. Good quality of life, reasonable cost of living outside Milwaukee.",
    websiteUrl: "https://www.dhs.wisconsin.gov",
  },
  WY: {
    stateCode: "WY",
    stateName: "Wyoming",
    conradSlots: 30,
    flexSlots: 5,
    timeline: "6-10 months (very fast processing)",
    processingTime: "45-60 days — among the fastest",
    priorityAreas: ["Primary Care", "Rural Health", "Frontier Health"],
    specialtyNeeds: ["Family Medicine", "Emergency Medicine", "General Surgery", "Internal Medicine"],
    requirements:
      "Must practice in a HPSA or MUA for 3 years. Wyoming DOH sponsors Conrad 30 applications. Wyoming typically uses only 8-10 of its 30 slots — 20+ remaining most years. 70% of Wyoming's Conrad placements are flex waivers (second highest nationally). No alternative regional pathways. Full unrestricted WY medical license required.",
    tips: "Wyoming is the least competitive waiver state in the nation — typically 20+ slots remaining all year. 70% of placements are flex waivers. Processing is very fast (45-60 days). No state income tax. Nearly every community is HPSA-designated. Expect a truly rural lifestyle — the state's entire population is under 600,000. Casper, Cheyenne, and Laramie are the 'largest' cities. If you're comfortable with small-town medicine and outdoor life, Wyoming offers certainty of placement, fast processing, and no tax burden. WWAMI program (UW partnership with University of Washington) provides some academic connection.",
    websiteUrl: "https://health.wyo.gov",
  },
};

export function getWaiverStateByCode(code: string): WaiverState | null {
  return WAIVER_STATES[code.toUpperCase()] || null;
}

export function getWaiverStateBySlug(slug: string): WaiverState | null {
  const entry = Object.values(WAIVER_STATES).find(
    (s) => s.stateName.toLowerCase().replace(/\s+/g, "-") === slug.toLowerCase()
  );
  return entry || null;
}

export function getAllWaiverStateSlugs(): { state: string }[] {
  return Object.values(WAIVER_STATES).map((s) => ({
    state: s.stateName.toLowerCase().replace(/\s+/g, "-"),
  }));
}
