// AUTO-GENERATED by scripts/generate-micro-pilot-runtime.ts
// Source: T7 prep CSV at commit 3b9d0fa + slice append per
//   docs/platform-v2/local/usce-completeness/staged-runtime-batch-3-noindex-activation-slice-1/
// Generated: 2026-05-10T00:00:00Z
// DO NOT EDIT — regenerate with: npx tsx scripts/generate-micro-pilot-runtime.ts

import type { UsceCard } from "@/lib/usce-maine-data";

export const PILOT_USCE_CARDS: UsceCard[] = [
  {
    "listing_id": "pilot-001-NJ-morristown-medical-center",
    "institution_name": "Morristown Medical Center",
    "campus_name": "",
    "state": "NJ",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SPECIALTY_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO",
      "CARIBBEAN_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE"
    ],
    "restriction_tags": [
      "NAMED_SCHOOLS_ONLY",
      "MS3_AND_MS4",
      "MS4_SPACE_PERMITTING",
      "HOUSING_NOT_PROVIDED",
      "VSLO_EXCEPT_SGUSOM",
      "NO_BROAD_IMG_CLAIM",
      "NAMED_PARTNER_SGU_SOM"
    ],
    "fit_warnings": [
      "NAMED_SCHOOLS_ONLY",
      "HOUSING_NOT_PROVIDED",
      "NO_BROAD_IMG_CLAIM"
    ],
    "audience_detail": {
      "us_md_do": "ONLY_IF_AFFILIATED",
      "international_student": "UNKNOWN_NOT_STATED",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "ONLY_IF_AFFILIATED"
    },
    "application_url": "",
    "official_source_url": "https://ahs.atlantichealth.org/professionals-medical-education/medical-students.html",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-002-NJ-overlook-medical-center",
    "institution_name": "Overlook Medical Center",
    "campus_name": "",
    "state": "NJ",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SPECIALTY_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO",
      "CARIBBEAN_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE"
    ],
    "restriction_tags": [
      "NAMED_SCHOOLS_ONLY",
      "MS3_AND_MS4",
      "MS4_SPACE_PERMITTING",
      "HOUSING_NOT_PROVIDED",
      "VSLO_EXCEPT_SGUSOM",
      "NO_BROAD_IMG_CLAIM",
      "NAMED_PARTNER_SGU_SOM",
      "SIBLING_SITE_TO_MORRISTOWN"
    ],
    "fit_warnings": [
      "NAMED_SCHOOLS_ONLY",
      "HOUSING_NOT_PROVIDED",
      "NO_BROAD_IMG_CLAIM"
    ],
    "audience_detail": {
      "us_md_do": "ONLY_IF_AFFILIATED",
      "international_student": "UNKNOWN_NOT_STATED",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "ONLY_IF_AFFILIATED"
    },
    "application_url": "",
    "official_source_url": "https://ahs.atlantichealth.org/professionals-medical-education/medical-students.html",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-003-OH-cleveland-clinic-mercy-hospital",
    "institution_name": "Cleveland Clinic Mercy Hospital",
    "campus_name": "Cleveland Clinic Mercy",
    "state": "OH",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "POLICY_HUB",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_IMG_RELEVANT",
    "eligible_audiences": [
      "US_MD_DO",
      "INTERNATIONAL_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED",
      "MAX_TWO_APPLICATIONS"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "ELIGIBLE_EXPLICIT",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://my.clevelandclinic.org/departments/elective-program/requirements",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-004-OH-cleveland-clinic-hillcrest-hospital",
    "institution_name": "Cleveland Clinic Hillcrest Hospital",
    "campus_name": "Cleveland Clinic Hillcrest",
    "state": "OH",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "POLICY_HUB",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_IMG_RELEVANT",
    "eligible_audiences": [
      "US_MD_DO",
      "INTERNATIONAL_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED",
      "MAX_TWO_APPLICATIONS",
      "SYSTEM_PAGE_SOURCE_NO_HILLCREST_SPECIFIC_GUARANTEE"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED",
      "SYSTEM_PAGE_NO_SITE_SPECIFIC_GUARANTEE"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "ELIGIBLE_EXPLICIT",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://my.clevelandclinic.org/departments/elective-program/requirements",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-007-CA-highland-hospital-alameda-health-system",
    "institution_name": "Highland Hospital (Alameda Health System)",
    "campus_name": "Highland",
    "state": "CA",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SPECIALTY_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "DIVERSITY_SCHOLARSHIP_AVAILABLE",
      "MS4_ONLY",
      "DIVERSITY_ELIGIBILITY_REQUIRED",
      "GOOD_ACADEMIC_STANDING_REQUIRED",
      "FEE_NOT_MENTIONED"
    ],
    "fit_warnings": [
      "MS4_ONLY",
      "DIVERSITY_ELIGIBILITY_REQUIRED"
    ],
    "audience_detail": {
      "us_md_do": "ONLY_IF_AFFILIATED",
      "international_student": "UNKNOWN_NOT_STATED",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://www.highlandmedicine.org/visiting-elective-scholarship",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-014-NC-duke-university-hospital",
    "institution_name": "Duke University Hospital",
    "campus_name": "Duke School of Medicine visiting-students office",
    "state": "NC",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SYSTEM_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO"
    ],
    "excluded_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "unknown_audiences": [],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "COCA_OSTEO_ALSO_ELIGIBLE",
      "VSLO_REQUIRED",
      "VISA_NOT_MENTIONED_US_ONLY_AUDIENCE",
      "NO_J1_VERIFIED",
      "NO_H1B_VERIFIED"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "VSLO_REQUIRED"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "EXCLUDED_EXPLICIT",
      "img_graduate": "EXCLUDED_EXPLICIT",
      "caribbean_student": "EXCLUDED_EXPLICIT"
    },
    "application_url": "",
    "official_source_url": "https://medschool.duke.edu/education/health-professions-education-programs/student-services/office-registrar/visiting-students",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-09T00:00:00Z"
  },
  {
    "listing_id": "pilot-017-NY-nyu-langone-tisch-hospital",
    "institution_name": "NYU Langone Health - Tisch Hospital",
    "campus_name": "Site-level Tisch Hospital under NYU Langone Health",
    "state": "NY",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SYSTEM_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO"
    ],
    "excluded_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "unknown_audiences": [],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "VISA_NOT_MENTIONED_US_ONLY_AUDIENCE",
      "NO_J1_VERIFIED",
      "NO_H1B_VERIFIED"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "EXCLUDED_EXPLICIT",
      "img_graduate": "EXCLUDED_EXPLICIT",
      "caribbean_student": "EXCLUDED_EXPLICIT"
    },
    "application_url": "",
    "official_source_url": "https://med.nyu.edu/education/md-degree/registration-student-records/information-visiting-md-students",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-09T00:00:00Z"
  },
  {
    "listing_id": "pilot-019-IN-iu-health-methodist-hospital",
    "institution_name": "Indiana University Health Methodist Hospital",
    "campus_name": "Site-level IU Health Methodist Hospital under IU SOM",
    "state": "IN",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SYSTEM_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO"
    ],
    "excluded_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "unknown_audiences": [],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "VISA_NOT_MENTIONED_US_ONLY_AUDIENCE",
      "NO_J1_VERIFIED",
      "NO_H1B_VERIFIED"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "EXCLUDED_EXPLICIT",
      "img_graduate": "EXCLUDED_EXPLICIT",
      "caribbean_student": "EXCLUDED_EXPLICIT"
    },
    "application_url": "",
    "official_source_url": "https://medicine.iu.edu/md/admissions/guest-students",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-09T00:00:00Z"
  }
];

export const PILOT_IMG_RELEVANT_COUNT = 2;
export const PILOT_US_ONLY_COUNT = 6;
export const PILOT_TOTAL_COUNT = 8;
