// AUTO-GENERATED by P99-P97-RUNTIME-GENERATION-BATCH-2-STAGED-DATA-ONLY
// STAGED DATA ONLY — NOT IMPORTED BY APP CODE.
// This file is intentionally not imported by:
//   - src/lib/usce-pilot-data.ts
//   - src/app/clerkships/pilot/page.tsx
//   - src/app/clerkships/pilot/PilotClerkshipListings.tsx
// Importing this from the active route is a release-blocking error.
// Generated: 2026-05-09T00:00:00Z
// DO NOT EDIT — see the docs sprint folder for provenance:
//   docs/platform-v2/local/usce-completeness/runtime-generation-batch-2-staged-data-only/

import type { UsceCard } from "@/lib/usce-maine-data";

export const PILOT_USCE_CARDS_STAGED_BATCH_2_METADATA = {
  staged_only: true,
  not_imported_by_app: true,
  not_production: true,
  not_public_now: true,
  not_import_ready: true,
  candidate_status: "STAGED_DATA_ONLY_NOT_IMPORTED_BY_APP",
  staged_at: "2026-05-09T00:00:00Z",
  source: "P99-P97-RUNTIME-GENERATION-BATCH-2-STAGED-DATA-ONLY",
  active_runtime_unchanged: true,
  active_runtime_path: "src/data/usce/public-listings-pilot.generated.json",
  active_runtime_card_count: 5,
  staged_card_count: 7,
} as const;

export const PILOT_USCE_CARDS_STAGED_BATCH_2: UsceCard[] = 
[
  {
    "listing_id": "pilot-001-NJ-morristown-medical-center",
    "institution_name": "Morristown Medical Center",
    "campus_name": "",
    "state": "NJ",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SPECIALTY_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO",
      "CARIBBEAN_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE"
    ],
    "restriction_tags": [
      "NAMED_SCHOOLS_ONLY",
      "MS3_AND_MS4",
      "MS4_SPACE_PERMITTING",
      "HOUSING_NOT_PROVIDED",
      "VSLO_EXCEPT_SGUSOM",
      "NO_BROAD_IMG_CLAIM",
      "NAMED_PARTNER_SGU_SOM"
    ],
    "fit_warnings": [
      "NAMED_SCHOOLS_ONLY",
      "HOUSING_NOT_PROVIDED",
      "NO_BROAD_IMG_CLAIM"
    ],
    "audience_detail": {
      "us_md_do": "ONLY_IF_AFFILIATED",
      "international_student": "UNKNOWN_NOT_STATED",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "ONLY_IF_AFFILIATED"
    },
    "application_url": "",
    "official_source_url": "https://ahs.atlantichealth.org/professionals-medical-education/medical-students.html",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-002-NJ-overlook-medical-center",
    "institution_name": "Overlook Medical Center",
    "campus_name": "",
    "state": "NJ",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SPECIALTY_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO",
      "CARIBBEAN_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE"
    ],
    "restriction_tags": [
      "NAMED_SCHOOLS_ONLY",
      "MS3_AND_MS4",
      "MS4_SPACE_PERMITTING",
      "HOUSING_NOT_PROVIDED",
      "VSLO_EXCEPT_SGUSOM",
      "NO_BROAD_IMG_CLAIM",
      "NAMED_PARTNER_SGU_SOM",
      "SIBLING_SITE_TO_MORRISTOWN"
    ],
    "fit_warnings": [
      "NAMED_SCHOOLS_ONLY",
      "HOUSING_NOT_PROVIDED",
      "NO_BROAD_IMG_CLAIM"
    ],
    "audience_detail": {
      "us_md_do": "ONLY_IF_AFFILIATED",
      "international_student": "UNKNOWN_NOT_STATED",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "ONLY_IF_AFFILIATED"
    },
    "application_url": "",
    "official_source_url": "https://ahs.atlantichealth.org/professionals-medical-education/medical-students.html",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-003-OH-cleveland-clinic-mercy-hospital",
    "institution_name": "Cleveland Clinic Mercy Hospital",
    "campus_name": "Cleveland Clinic Mercy",
    "state": "OH",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "POLICY_HUB",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_IMG_RELEVANT",
    "eligible_audiences": [
      "US_MD_DO",
      "INTERNATIONAL_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED",
      "MAX_TWO_APPLICATIONS"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "ELIGIBLE_EXPLICIT",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://my.clevelandclinic.org/departments/elective-program/requirements",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-004-OH-cleveland-clinic-hillcrest-hospital",
    "institution_name": "Cleveland Clinic Hillcrest Hospital",
    "campus_name": "Cleveland Clinic Hillcrest",
    "state": "OH",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "POLICY_HUB",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_IMG_RELEVANT",
    "eligible_audiences": [
      "US_MD_DO",
      "INTERNATIONAL_STUDENT"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED",
      "MAX_TWO_APPLICATIONS",
      "SYSTEM_PAGE_SOURCE_NO_HILLCREST_SPECIFIC_GUARANTEE"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "FEE_REQUIRED",
      "SYSTEM_PAGE_NO_SITE_SPECIFIC_GUARANTEE"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "ELIGIBLE_EXPLICIT",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://my.clevelandclinic.org/departments/elective-program/requirements",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-007-CA-highland-hospital-alameda-health-system",
    "institution_name": "Highland Hospital (Alameda Health System)",
    "campus_name": "Highland",
    "state": "CA",
    "county": "",
    "specialty": "multispecialty_visiting",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SPECIALTY_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO"
    ],
    "excluded_audiences": [],
    "unknown_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "DIVERSITY_SCHOLARSHIP_AVAILABLE",
      "MS4_ONLY",
      "DIVERSITY_ELIGIBILITY_REQUIRED",
      "GOOD_ACADEMIC_STANDING_REQUIRED",
      "FEE_NOT_MENTIONED"
    ],
    "fit_warnings": [
      "MS4_ONLY",
      "DIVERSITY_ELIGIBILITY_REQUIRED"
    ],
    "audience_detail": {
      "us_md_do": "ONLY_IF_AFFILIATED",
      "international_student": "UNKNOWN_NOT_STATED",
      "img_graduate": "UNKNOWN_NOT_STATED",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://www.highlandmedicine.org/visiting-elective-scholarship",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-07T00:00:00Z"
  },
  {
    "listing_id": "pilot-011-PA-upmc-western-psychiatric-hospital",
    "institution_name": "UPMC Western Psychiatric Hospital",
    "campus_name": "System-level UPSOM/UPMC source \u2014 Western Psychiatric site placement not separately enumerated",
    "state": "PA",
    "county": "",
    "specialty": "multispecialty_visiting_psychiatry_step2_required",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SYSTEM_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_IMG_RELEVANT",
    "eligible_audiences": [
      "US_MD_DO",
      "INTERNATIONAL_STUDENT"
    ],
    "excluded_audiences": [
      "IMG_GRADUATE"
    ],
    "unknown_audiences": [
      "CARIBBEAN_STUDENT"
    ],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "MS4_ONLY",
      "VSLO_EXCEPT_SGUSOM",
      "FEE_REQUIRED",
      "MAX_TWO_APPLICATIONS",
      "VISA_APPLICANT_OBTAINED_B1",
      "NO_J1_SPONSORSHIP",
      "NO_H1B_SPONSORSHIP",
      "SYSTEM_PAGE_SOURCE_NO_WPIC_SPECIFIC_GUARANTEE",
      "STEP_2_REQUIRED_FOR_PSYCHIATRIC_ELECTIVE",
      "NO_OBSERVERSHIP_FOR_GRADUATES"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "FEE_REQUIRED",
      "MS4_ONLY",
      "SYSTEM_PAGE_SOURCE_NO_WPIC_SPECIFIC_GUARANTEE"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "ONLY_IF_AFFILIATED",
      "img_graduate": "EXCLUDED_EXPLICIT",
      "caribbean_student": "UNKNOWN_NOT_STATED"
    },
    "application_url": "",
    "official_source_url": "https://www.medstudentaffairs.pitt.edu/visiting-students",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-09T00:00:00Z"
  },
  {
    "listing_id": "pilot-012-NY-nyc-health-hospitals-lincoln",
    "institution_name": "NYC Health + Hospitals/Lincoln",
    "campus_name": "System-level NYC H+H MOSAIC source \u2014 Lincoln site placement not separately enumerated",
    "state": "NY",
    "county": "",
    "specialty": "multispecialty_visiting_em_site_specific_secondary",
    "opportunity_type": "Visiting elective",
    "source_page_type": "SYSTEM_PAGE",
    "listing_role": "PUBLIC_OPPORTUNITY",
    "display_bucket": "READY_PUBLIC_US_STUDENT_ONLY",
    "eligible_audiences": [
      "US_MD_DO"
    ],
    "excluded_audiences": [
      "INTERNATIONAL_STUDENT",
      "IMG_GRADUATE",
      "CARIBBEAN_STUDENT"
    ],
    "unknown_audiences": [],
    "restriction_tags": [
      "LCME_AOA_ONLY",
      "FEE_NOT_MENTIONED",
      "STIPEND_PROVIDED",
      "HOUSING_STIPEND_NON_NYC_METRO",
      "SYSTEM_PAGE_SOURCE_NO_LINCOLN_SPECIFIC_GUARANTEE",
      "EM_SITE_SPECIFIC_SECONDARY_SOURCE",
      "URM_ENCOURAGED"
    ],
    "fit_warnings": [
      "LCME_AOA_ONLY",
      "SYSTEM_PAGE_SOURCE_NO_LINCOLN_SPECIFIC_GUARANTEE",
      "STIPEND_PROVIDED"
    ],
    "audience_detail": {
      "us_md_do": "ELIGIBLE_EXPLICIT",
      "international_student": "EXCLUDED_EXPLICIT",
      "img_graduate": "EXCLUDED_EXPLICIT",
      "caribbean_student": "EXCLUDED_EXPLICIT"
    },
    "application_url": "",
    "official_source_url": "https://www.nychealthandhospitals.org/mosaic/visiting-scholars-program/",
    "source_status": "OFFICIAL_SOURCE_ARCHIVED",
    "last_reviewed_at": "2026-05-09T00:00:00Z"
  }
]
;

export const PILOT_STAGED_BATCH_2_IMG_RELEVANT_COUNT = 3;
export const PILOT_STAGED_BATCH_2_US_ONLY_COUNT = 4;
export const PILOT_STAGED_BATCH_2_TOTAL_COUNT = 7;
