// AUTO-GENERATED by scripts/visa-job-radar/run.ts — do not edit by hand.
// Only PUBLISH-bucket, non-fixture jobs are emitted here.

export interface VisaRadarJob {
  id: string;
  employer: string;
  title: string;
  city?: string;
  state?: string;
  sourceId: string;
  sourceUrl: string;
  postedDate?: string;
  visaLabels: string[];
  evidence: string[];
  confidence: string;
}

export const RADAR_META = {
  lastRun: "2026-05-30T00:32:31.947Z",
  jobCount: 0,
  note: "No live source configured yet; the deterministic engine is verified on fixtures only. This file is intentionally empty until a Tier-1 connector is enabled.",
} as const;

export const VISA_JOBS_RADAR: VisaRadarJob[] = [];
