"""
P98-2: Institution ↔ NPPES matcher

Deterministic scoring ladder:
  VERIFIED_EXACT_NPI   — institution packet already has a confirmed NPI (future)
  EXACT_NAME_ZIP       — normalized org_name exact match + ZIP prefix
  EXACT_NAME_CITY      — normalized org_name exact match + city
  FUZZY_NAME_ZIP       — fuzzy name match (Levenshtein ≤ 2 tokens differ) + ZIP prefix
  FUZZY_NAME_CITY      — fuzzy name match + city
  NAME_ONLY            — name-only match (no address signal), lowest confidence
  NO_NPPES_MATCH       — no candidate found

No LLM scoring until candidates are generated by the deterministic pass.

Output:
  match_results.csv — one row per institution, best match + runner-up
  match_candidates.csv — all candidates for manual review workbench

Run: python3 match_institutions.py [--state ME]
"""

import argparse
import csv
import json
import os
import re
import sys
import unicodedata
from difflib import SequenceMatcher
from pathlib import Path

import duckdb

DB_PATH = Path(__file__).parent / "nppes_orgs.duckdb"
PROGRESS_CSV = (
    Path(__file__).parent.parent / "p97_institution_search_progress.csv"
)
RESULTS_CSV = Path(__file__).parent / "match_results.csv"
CANDIDATES_CSV = Path(__file__).parent / "match_candidates.csv"

MATCH_TIERS = [
    "VERIFIED_EXACT_NPI",
    "EXACT_NAME_ZIP",
    "EXACT_NAME_CITY",
    "FUZZY_NAME_ZIP",
    "FUZZY_NAME_CITY",
    "NAME_ONLY",
    "NO_NPPES_MATCH",
]

# Hospital-type taxonomy prefixes to prefer in candidate ranking
HOSPITAL_TAXONOMY_PREFIXES = ("282N", "273Y", "276", "286", "261QF", "451")


def strip_parens(s: str) -> str:
    """
    Remove parenthetical abbreviations (MMC), (EMMC), etc. and slash-separated
    alternate names ('Central Maine Medical Center / Central Maine Healthcare'
    → 'Central Maine Medical Center') to prevent doubled tokens inflating similarity.
    """
    s = re.sub(r"\s*\([^)]*\)", "", s)  # remove (...)
    s = re.sub(r"\s*/.*$", "", s)       # remove / and everything after (take primary name only)
    return s.strip()


def normalize(s: str) -> str:
    """Lowercase, strip accents, collapse whitespace, remove punctuation except spaces."""
    if not s:
        return ""
    s = unicodedata.normalize("NFD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.lower()
    s = re.sub(r"[^\w\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


# Common suffixes/words to strip for fuzzy matching
STRIP_WORDS = {
    "hospital",
    "medical center",
    "health center",
    "health system",
    "healthcare",
    "health care",
    "regional medical center",
    "community hospital",
    "memorial hospital",
    "general hospital",
    "university hospital",
    "the",
    "llc",
    "inc",
    "corporation",
    "corp",
}


def core_name(s: str) -> str:
    """Strip common hospital suffixes for fuzzy token comparison."""
    n = normalize(s)
    for w in STRIP_WORDS:
        n = re.sub(r"\b" + re.escape(w) + r"\b", "", n)
    return re.sub(r"\s+", " ", n).strip()


def zip_prefix(z: str) -> str:
    return (z or "")[:5]


def name_similarity(a: str, b: str) -> float:
    return SequenceMatcher(None, core_name(a), core_name(b)).ratio()


def is_hospital_taxonomy(code: str) -> bool:
    return any((code or "").startswith(p) for p in HOSPITAL_TAXONOMY_PREFIXES)


def load_institutions(state_filter) -> list[dict]:  # str | None
    institutions = []
    with open(PROGRESS_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if state_filter and row["state"] != state_filter:
                continue
            institutions.append(
                {
                    "state": row["state"],
                    "county": row["county"],
                    "institution_name": row["institutionName"],
                    "institution_type": row.get("institutionType", ""),
                    "official_website": row.get("officialWebsite", ""),
                    "health_system": row.get("healthSystem", ""),
                }
            )
    return institutions


def find_candidates(
    con, state: str, name_norm: str, name_core: str
) -> list[dict]:
    """
    Query NPPES for orgs in state matching significant words from name.

    Strategy: prefer AND-match on multiple sig_words (precise); fall back to
    OR-match when AND returns too few. This prevents the OR '%maine%' problem
    where every ME org matches and the right record falls beyond LIMIT.
    """
    # Extract significant words (>3 chars) from core name, excluding very common words
    COMMON = {"care", "health", "center", "medical", "services", "service",
              "system", "systems", "clinic", "group", "practice", "associates"}
    sig_words = [w for w in name_core.split() if len(w) > 3 and w not in COMMON]
    if not sig_words:
        # Fall back to longest words from normalized full name
        all_words = sorted(
            [w for w in name_norm.split() if len(w) > 3], key=len, reverse=True
        )
        sig_words = all_words[:3]

    def run_query(clauses: str, limit: int) -> list:
        return con.execute(
            f"""
            SELECT npi, org_name, other_name, pl_addr1, pl_city, pl_state, pl_zip,
                   mail_city, mail_state, mail_zip,
                   taxonomy_1, taxonomy_2, is_subpart, parent_org_name,
                   deactivation_date
            FROM nppes_orgs
            WHERE pl_state = ?
              AND ({clauses})
            ORDER BY org_name
            LIMIT {limit}
            """,
            [state],
        ).fetchall()

    # Try AND on all sig_words first (most precise)
    if len(sig_words) >= 2:
        and_clauses = " AND ".join(
            [f"LOWER(org_name) LIKE '%{w}%'" for w in sig_words[:4]]
        )
        rows = run_query(and_clauses, 500)
        if len(rows) >= 1:
            return _to_dicts(rows)

    # Fall back: OR on sig_words, but with higher limit
    or_clauses = " OR ".join(
        [f"LOWER(org_name) LIKE '%{w}%'" for w in sig_words[:5]]
    )
    rows = run_query(or_clauses, 500)
    return _to_dicts(rows)


def _to_dicts(rows: list) -> list[dict]:
    cols = [
        "npi", "org_name", "other_name", "pl_addr1", "pl_city", "pl_state", "pl_zip",
        "mail_city", "mail_state", "mail_zip",
        "taxonomy_1", "taxonomy_2", "is_subpart", "parent_org_name",
        "deactivation_date",
    ]
    return [dict(zip(cols, r)) for r in rows]


def score_candidate(
    target_name: str,
    target_state: str,
    cand: dict,
) -> tuple:  # (str, float)
    """
    Returns (tier, confidence_score 0.0-1.0).
    Strips parenthetical abbreviations (MMC, EMMC, etc.) before scoring.
    """
    # Strip parens from target before comparison
    clean_target = strip_parens(target_name)
    tname_norm = normalize(clean_target)

    cname_norm = normalize(cand["org_name"] or "")
    cother_norm = normalize(cand["other_name"] or "")

    # Use best of legal name vs other name
    sim_legal = name_similarity(clean_target, cand["org_name"] or "")
    sim_other = name_similarity(clean_target, cand["other_name"] or "")
    if sim_other > sim_legal and cand["other_name"]:
        best_norm = cother_norm
        best_name = cand["other_name"]
        sim = sim_other
    else:
        best_norm = cname_norm
        best_name = cand["org_name"] or ""
        sim = sim_legal

    exact_norm = tname_norm == best_norm

    pl_zip5 = zip_prefix(cand["pl_zip"])
    mail_zip5 = zip_prefix(cand["mail_zip"])
    pl_city_norm = normalize(cand["pl_city"])
    mail_city_norm = normalize(cand["mail_city"])

    # Address signal: candidate has a non-empty address (all NPPES records do).
    # We treat this as "address present" rather than comparing against target ZIP/city
    # (we don't have target city/ZIP in the institution progress CSV).
    # P98-3 reviewer will confirm address match against CMS CCN / official website data.
    has_address = bool(pl_zip5 or mail_zip5)
    has_city = bool(pl_city_norm or mail_city_norm)

    if exact_norm and has_address:
        return "EXACT_NAME_ZIP", 0.95
    if exact_norm and has_city:
        return "EXACT_NAME_CITY", 0.85
    if sim >= 0.80 and has_address:
        return "FUZZY_NAME_ZIP", 0.75
    if sim >= 0.80 and has_city:
        return "FUZZY_NAME_CITY", 0.65
    if sim >= 0.60:
        return "NAME_ONLY", round(0.40 + sim * 0.1, 3)
    return "NAME_ONLY", round(sim * 0.5, 3)


def tier_rank(tier: str) -> int:
    return MATCH_TIERS.index(tier) if tier in MATCH_TIERS else len(MATCH_TIERS)


def match_institution(con, inst):  # -> tuple[dict | None, list[dict]]
    """
    Returns (best_match_row, all_candidates_with_scores).
    """
    name = inst["institution_name"]
    state = inst["state"]
    clean_name = strip_parens(name)  # remove (MMC), (EMMC), (Psychiatry) etc.
    name_norm = normalize(clean_name)
    name_core_str = core_name(clean_name)

    candidates = find_candidates(con, state, name_norm, name_core_str)


    if not candidates:
        return None, []

    scored = []
    for c in candidates:
        tier, conf = score_candidate(name, state, c)
        if tier == "NO_NPPES_MATCH":
            continue
        scored.append(
            {
                **c,
                "match_tier": tier,
                "confidence": round(conf, 3),
                "is_hospital_taxonomy": is_hospital_taxonomy(c["taxonomy_1"]),
                "target_institution_name": name,
                "target_state": state,
                "target_county": inst["county"],
            }
        )

    if not scored:
        return None, []

    # Sort: tier rank ASC, then hospital taxonomy DESC, then confidence DESC
    scored.sort(
        key=lambda r: (
            tier_rank(r["match_tier"]),
            0 if r["is_hospital_taxonomy"] else 1,
            -r["confidence"],
        )
    )

    return scored[0], scored


def write_results(
    results: list[dict], candidates: list[dict]
) -> None:
    result_fields = [
        "state", "county", "institution_name",
        "match_tier", "confidence",
        "npi", "org_name", "pl_addr1", "pl_city", "pl_state", "pl_zip",
        "taxonomy_1", "is_hospital_taxonomy", "deactivation_date",
        "runner_up_npi", "runner_up_name", "runner_up_tier", "runner_up_conf",
        "candidate_count",
    ]
    cand_fields = [
        "target_institution_name", "target_state", "target_county",
        "match_tier", "confidence", "is_hospital_taxonomy",
        "npi", "org_name", "other_name", "pl_addr1", "pl_city", "pl_state", "pl_zip",
        "taxonomy_1", "taxonomy_2", "is_subpart", "parent_org_name", "deactivation_date",
    ]

    with open(RESULTS_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=result_fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(results)

    with open(CANDIDATES_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=cand_fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(candidates)

    print(f"\nResults: {RESULTS_CSV} ({len(results)} rows)")
    print(f"Candidates: {CANDIDATES_CSV} ({len(candidates)} rows)")


def main():
    parser = argparse.ArgumentParser(description="P98-2 Institution ↔ NPPES matcher")
    parser.add_argument("--state", default="ME", help="State abbreviation to run (default: ME)")
    args = parser.parse_args()

    if not DB_PATH.exists():
        sys.exit(f"ERROR: NPPES DB not found at {DB_PATH}. Run ingest_nppes.py first.")

    if not PROGRESS_CSV.exists():
        sys.exit(f"ERROR: Institution progress CSV not found at {PROGRESS_CSV}")

    institutions = load_institutions(args.state)
    print(f"Institutions to match: {len(institutions)} ({args.state})")

    con = duckdb.connect(str(DB_PATH), read_only=True)

    result_rows = []
    all_candidates = []

    for inst in institutions:
        name = inst["institution_name"]
        best, cands = match_institution(con, inst)

        runner_up = cands[1] if len(cands) > 1 else None

        if best is None:
            row = {
                "state": inst["state"],
                "county": inst["county"],
                "institution_name": name,
                "match_tier": "NO_NPPES_MATCH",
                "confidence": 0.0,
                "npi": "",
                "org_name": "",
                "pl_addr1": "",
                "pl_city": "",
                "pl_state": "",
                "pl_zip": "",
                "taxonomy_1": "",
                "is_hospital_taxonomy": False,
                "deactivation_date": "",
                "runner_up_npi": "",
                "runner_up_name": "",
                "runner_up_tier": "",
                "runner_up_conf": "",
                "candidate_count": 0,
            }
        else:
            row = {
                "state": inst["state"],
                "county": inst["county"],
                "institution_name": name,
                "match_tier": best["match_tier"],
                "confidence": best["confidence"],
                "npi": best["npi"],
                "org_name": best["org_name"],
                "pl_addr1": best["pl_addr1"],
                "pl_city": best["pl_city"],
                "pl_state": best["pl_state"],
                "pl_zip": best["pl_zip"],
                "taxonomy_1": best["taxonomy_1"],
                "is_hospital_taxonomy": best["is_hospital_taxonomy"],
                "deactivation_date": best["deactivation_date"],
                "runner_up_npi": runner_up["npi"] if runner_up else "",
                "runner_up_name": runner_up["org_name"] if runner_up else "",
                "runner_up_tier": runner_up["match_tier"] if runner_up else "",
                "runner_up_conf": runner_up["confidence"] if runner_up else "",
                "candidate_count": len(cands),
            }

        result_rows.append(row)
        all_candidates.extend(cands)

        tier_label = row["match_tier"]
        npi_label = row["npi"] or "—"
        print(f"  [{tier_label:20s}] {name[:50]:50s}  NPI={npi_label}")

    con.close()

    write_results(result_rows, all_candidates)

    # Summary
    print("\n=== Match Summary ===")
    tier_counts: dict[str, int] = {}
    for r in result_rows:
        tier_counts[r["match_tier"]] = tier_counts.get(r["match_tier"], 0) + 1
    for tier in MATCH_TIERS:
        if tier in tier_counts:
            print(f"  {tier:30s}: {tier_counts[tier]}")

    matched = sum(1 for r in result_rows if r["match_tier"] != "NO_NPPES_MATCH")
    print(f"\nMatched: {matched}/{len(result_rows)} ({100*matched//len(result_rows)}%)")
    print("\nNOTE: All matches require human review in the P98-3 review workbench.")
    print("      NPPES is identity/location evidence only — not credential verification.")


if __name__ == "__main__":
    main()
