// Visa Job Radar — source registry.
//
// Tier 1 = clean, employer-direct or government provenance (publishable).
// Tier 2 = experimental / aggregated provenance (held as signal, reviewed).
// Tier 3 = never crawled; listed only so the engine can explicitly refuse.
//
// `enabled` stays false until a token/endpoint is verified by hand. The R1
// offline run touches none of these — they are wired by the connectors in a
// later phase. Greenhouse tokens below are placeholders pending verification.

import type { SourceTier } from "./types";

export type Connector =
  | "usajobs"
  | "usajobs-historic"
  | "greenhouse"
  | "workday"
  | "jsonld"
  | "jibe"
  | "findly"
  | "atom"
  | "avature-rss"
  | "none";

export interface SourceDef {
  id: string;
  tier: SourceTier;
  connector: Connector;
  label: string;
  // connector-specific handle (USAJobs keyword, Greenhouse board token, etc.)
  handle: string;
  employer?: string;
  enabled: boolean;
  needsVerification: boolean;
  note: string;
  // Jibe connectors only: replaces default "keyword=physician" query string
  jibeQuery?: string;
}

export const SOURCES: SourceDef[] = [
  {
    id: "usajobs-va-0602",
    tier: 1,
    connector: "usajobs",
    label: "USAJobs — VA/IHS physicians (series 0602)",
    handle: "physician",
    enabled: false,
    needsVerification: true,
    note: "Keyed Search API. Requires USAJOBS_API_KEY + USAJOBS_USER_AGENT (unprovisioned → off). Preferred for guaranteed-live openings once keyed.",
  },
  {
    id: "usajobs-historic-va-0602",
    tier: 1,
    connector: "usajobs-historic",
    label: "USAJobs HistoricJoa — VHA physicians (series 0602, no key)",
    handle: "0602/VATA",
    employer: "Veterans Health Administration",
    enabled: true,
    needsVerification: true,
    note: "Public no-key endpoints (historicjoa + announcementtext), joined on control number. Verified 2026-06-10: HTTP 200, full body text, ~100% of 0602 VHA postings carry the 38 U.S.C. 7407 non-citizen-eligibility clause (445/445 in a Feb window). Eligibility tier only — engine caps FEDERAL_NONCITIZEN_ELIGIBLE at VISA_SIGNAL_ONLY (statutory 'may appoint', not affirmative sponsorship).",
  },
  {
    id: "greenhouse-onemedical",
    tier: 1,
    connector: "greenhouse",
    label: "One Medical — primary care (Greenhouse)",
    handle: "onemedical",
    employer: "One Medical",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-12: 301 fetched per run, 0 PUBLISH, 0 SPONSOR_LEAD. One Medical is an Amazon-owned primary care clinic; their DOL LCA history is marginal (5yr, 1 pos) and fails the quality gate. Greenhouse board returns full all-staff listing (nurses, MAs, receptionists) — physician:noise ratio ~5%. Zero useful signal at high fetch cost.",
  },
  {
    id: "greenhouse-oscar",
    tier: 1,
    connector: "greenhouse",
    label: "Oscar Health — clinical (Greenhouse)",
    handle: "oscar",
    employer: "Oscar Health",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-12: 235 fetched per run, 0 PUBLISH, 0 SPONSOR_LEAD. Oscar is an insurance company (managed care), not a physician employer. Their Greenhouse board is for tech, ops, and care coordination roles — not physician attendings. No DOL H1B physician LCA history.",
  },
  {
    id: "greenhouse-cerebral",
    tier: 1,
    connector: "greenhouse",
    label: "Cerebral — psychiatry (Greenhouse)",
    handle: "cerebral",
    employer: "Cerebral",
    enabled: true,
    needsVerification: false,
    note: "Employer-direct ATS. Verified 2026-05-29: HTTP 200, physician + psychiatrist postings.",
  },
  {
    id: "workday-sanford",
    tier: 1,
    connector: "workday",
    label: "Sanford Health — physicians (Workday)",
    handle: "sanford/wd5/SanfordHealth",
    employer: "Sanford Health",
    enabled: true,
    needsVerification: true,
    note: "Employer-direct Workday tenant (unofficial CXS endpoint). Verified 2026-05-29: HTTP 200, ~1712 'physician' search hits. Rural mission system.",
  },
  {
    id: "workday-wvu-uha",
    tier: 1,
    connector: "workday",
    label: "WVU Medicine (UHA) — physicians (Workday)",
    handle: "wvumedicine/wd1/UHA",
    employer: "WVU Medicine",
    enabled: false,
    needsVerification: true,
    note: "DISABLED 2026-05-30: tenant is behind bot-protection. Serves curl but returns HTTP 500 to a plain Node client; only a request forging a browser User-Agent + Origin + Referer + Accept-Language succeeds. Reaching it would mean spoofing a browser to defeat bot detection — refused (same posture as HRSA). H-1B cap-exempt academic system, underserved WV; revisit only via a sanctioned feed.",
  },
  {
    id: "workday-wvu-wvuh",
    tier: 1,
    connector: "workday",
    label: "WVU Medicine (WVUH) — physicians (Workday)",
    handle: "wvumedicine/wd1/WVUH",
    employer: "WVU Medicine",
    enabled: false,
    needsVerification: true,
    note: "DISABLED 2026-05-30: same bot-protection as the UHA site (HTTP 500 to a plain Node client). Not bypassed.",
  },
  {
    id: "workday-altamed",
    tier: 1,
    connector: "workday",
    label: "AltaMed Health Services — physicians (Workday)",
    handle: "altamed/wd1/Careers",
    employer: "AltaMed Health Services",
    enabled: true,
    needsVerification: true,
    note: "Employer-direct Workday tenant (unofficial CXS endpoint). Verified 2026-05-29: HTTP 200, ~58 hits. Large multi-site FQHC (CA), high J-1 density.",
  },
  // Auto-resolved from the DOL sponsor universe (build-sponsor-universe.ts) via the
  // ATS resolver (ats-resolver.ts): top physician H-1B sponsors whose own careers
  // page runs a reachable Workday tenant. Handle = tenant/dc/site extracted from
  // their careers HTML, then CXS-verified 2026-06-10. These are KNOWN sponsors
  // from public DOL LCA data, so even a visa-silent posting carries a strong
  // sponsor-history prior.
  {
    id: "workday-clevelandclinic",
    tier: 1,
    connector: "workday",
    label: "Cleveland Clinic — physicians (Workday)",
    handle: "ccf/wd1/clevelandcliniccareers",
    employer: "Cleveland Clinic",
    enabled: false,
    needsVerification: true,
    note: "DISABLED 2026-06-12: clevelandcliniccareers Workday portal is for non-physician staff only. Full-portal scan: 1983 total jobs, only 10 in 'Physician - Job Family Group' — all Postdoctoral Fellows. Cleveland Clinic physician attending/faculty recruitment is through a separate WordPress portal at jobs.clevelandclinic.org. Probe that portal for physician attending postings.",
  },
  {
    id: "workday-uams",
    tier: 1,
    connector: "workday",
    label: "Univ. of Arkansas for Medical Sciences — physicians (Workday)",
    handle: "uasys/wd5/uams_all_careers",
    employer: "University of Arkansas for Medical Sciences",
    enabled: true,
    needsVerification: true,
    note: "DOL sponsor universe (top-5 physician H-1B sponsor) → ATS-resolved. Verified 2026-06-10: CXS HTTP 200, ~103 'physician' hits.",
  },
  {
    id: "workday-msk",
    tier: 1,
    connector: "workday",
    label: "Memorial Sloan Kettering — physicians (Workday)",
    handle: "msk/wd108/mskcc_careers_primary",
    employer: "Memorial Sloan Kettering Cancer Center",
    enabled: true,
    needsVerification: true,
    note: "DOL sponsor universe (top-3 physician H-1B sponsor) → ATS-resolved. Resolver found the wd108 datacenter (a manual wd1 guess 422'd). Verified 2026-06-10: CXS HTTP 200, ~22 'physician' hits.",
  },
  {
    id: "workday-ochsner",
    tier: 1,
    connector: "workday",
    label: "Ochsner Health — physicians (Workday)",
    handle: "ochsner/wd1/ochsner",
    employer: "Ochsner Health",
    enabled: true,
    needsVerification: true,
    note: "DOL sponsor universe → batch ATS-resolved (scale-sponsors.ts). Verified 2026-06-10: CXS HTTP 200, ~786 'physician' hits. Large LA/Gulf-South system, high J-1-waiver density.",
  },
  {
    id: "workday-vumc",
    tier: 1,
    connector: "workday",
    label: "Vanderbilt University Medical Center — physicians (Workday)",
    handle: "vumc/wd1/vumccareers",
    employer: "Vanderbilt University Medical Center",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-12: vumccareers Workday portal does not expose attending/faculty physician postings. Full scan: 244 'physician' keyword hits, 0 actual MD/DO attending titles — every result is NP/PA, nursing, imaging tech, or support staff. The only isPhysician() pass was 'Pediatric Cardiac Sonographer II' (false positive on 'pediatric' PHYS token — fixed by adding 'sonographer' to NONPHYS_TOKENS). VUMC physician faculty are likely recruited via Vanderbilt University academic HR, not the clinical ATS. DOL iron-core sponsor (7yr). Revisit only if VUMC adds a physician-specific portal.",
  },
  {
    id: "workday-stanfordhealth",
    tier: 1,
    connector: "workday",
    label: "Stanford Health Care — physicians (Workday)",
    handle: "stanfordmedicine/wd115/shc_external_career_site",
    employer: "Stanford Health Care",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-13: shc_external_career_site does NOT carry attending physician postings. CXS returns 150 'physician' keyword hits but all are NP/PA, nursing, allied health — no MD/DO physician job category exists in facets. Same pattern as VUMC: physician faculty are recruited through Stanford University academic HR (Leland Stanford Jr. University), not the clinical ATS. DOL EMPLOYER_ALIAS 'stanford health care' → 'leland stanford jr university' remains valid. Revisit if SHC adds a physician-specific Workday site.",
  },
  {
    id: "workday-jeffersonhealth",
    tier: 1,
    connector: "workday",
    label: "Thomas Jefferson University Hospitals — physicians (Workday)",
    handle: "jeffersonhealth/wd5/thomasjeffersonexternal",
    employer: "Thomas Jefferson University Hospitals",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025) → batch ATS-resolved 2026-06-12. Verified: CXS HTTP 200, ~402 'physician' hits. PA academic medical center.",
  },
  {
    id: "workday-presbyterianhealthcare",
    tier: 1,
    connector: "workday",
    label: "Presbyterian Healthcare Services (NM) — physicians (Workday)",
    handle: "phsorg/wd1/careers",
    employer: "Presbyterian Healthcare Services",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025) → batch ATS-resolved 2026-06-12. Verified: CXS HTTP 200, ~307 'physician' hits. NM safety-net system, high J-1-waiver density.",
  },
  {
    id: "workday-montefiore",
    tier: 1,
    connector: "workday",
    label: "Montefiore Medical Center — physicians (Workday)",
    handle: "montefiore/wd12/MMC",
    employer: "Montefiore Medical Center",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years). Workday discovered 2026-06-12 via careers page redirect (vizi.vizirecruiter.com → wd12). Verified: CXS HTTP 200, total=397, Physician facet=126 jobs (id=54e1565c3bfa10053f2dc8a0674b0000). Major Bronx academic system, high J-1-waiver density (Bronx HPSA).",
  },
  // ── JSON-LD sources — community/regional iron-core sponsors ────────────────
  // ATS confirmed by scale-sponsors.ts probe (2026-06-12). handle = full
  // physician-filtered search URL. Employer-direct: no board is involved.
  // These are all DOL iron-core (7/7 years), so every opening is a sponsor-backed lead.
  // All start disabled; enable after verifying the URL returns physician postings.
  {
    id: "jsonld-froedtert",
    tier: 1,
    connector: "jsonld",
    label: "Froedtert Health — physicians (Infor CloudSuite)",
    handle: "https://css-froedterthealth-prd.inforcloudsuite.com",
    employer: "Froedtert Health",
    enabled: false,
    needsVerification: true,
    note: "DISABLED 2026-06-12: Step 2 probe mis-detected Phenom from careers.froedtert.com landing page — actual ATS is Infor CloudSuite HCM (css-froedterthealth-prd.inforcloudsuite.com). That domain returns HTTP 403 to a plain Node client (bot protection). Disabled — same posture as WVU. DOL iron-core (7/7 years). Revisit only via sanctioned feed.",
  },
  {
    id: "jsonld-mercy",
    tier: 1,
    connector: "jsonld",
    label: "Mercy Health — physicians (Phenom)",
    handle: "https://careers.mercy.com/us/en/search-results?keywords=physician",
    employer: "Mercy Health",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-12: Mercy Health does not post attending physician (MD/DO) jobs on careers.mercy.com. Full sitemap scan: 1,163 URLs across 3 sub-sitemaps — zero actual physician attending titles. Every 'physician' URL match is support staff (RN, CMA, LPN, Patient Services Rep at a physician's office) or a department name (Orthopedics, Cardiology). NONPHYS_SLUG_RE correctly excludes all URL-slug matches. DOL iron-core (7yr/138pos) — sponsorship is real but ATS surface carries only clinical support staff. Revisit only if Mercy adds a physician-specific careers portal.",
  },
  {
    id: "jsonld-tufts",
    tier: 1,
    connector: "jsonld",
    label: "Tufts Medical Center — physicians (Phenom)",
    handle: "https://careers.tuftsmedicine.org/us/en/search-results?keywords=physician",
    employer: "Tufts Medical Center",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years). ATS = Phenom; search page is a React SPA so fetchJsonLd uses the sitemap fallback (flat sitemap.xml, 438 /job/ URLs, ~68 physician-slug matches). Verified 2026-06-12: /job/R21325/Internal-Medicine-Physician returns @type:JobPosting with 15KB description. Boston community-teaching hospital.",
  },
  {
    id: "jsonld-umms",
    tier: 1,
    connector: "jsonld",
    label: "University of Maryland Medical System — physicians (Phenom)",
    handle: "https://careers.umms.org/us/en/search-results?keywords=physician",
    employer: "University of Maryland Medical System",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years). ATS = Phenom; search page is a React SPA so fetchJsonLd uses the sitemap fallback (sitemap_index.xml → 3 sub-sitemaps → 1496 /job/ URLs, ~104 physician-slug matches). Verified 2026-06-12: Neurohospitalist posting returns @type:JobPosting, org=UMMS, 6KB description. MD state system.",
  },
  {
    id: "jsonld-wellstar",
    tier: 1,
    connector: "jsonld",
    label: "Wellstar Medical Group — physicians (Phenom)",
    handle: "https://careers.wellstar.org/us/en/search-results?keywords=physician",
    employer: "Wellstar Medical Group",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 19 certified positions). ATS = Phenom (tenant WHWWHSUS). Search page is a React SPA; fetchJsonLd falls back to sitemap enumeration. careers.wellstar.org/sitemap.xml → sitemap_index.xml (3 sub-sitemaps) → sitemap2.xml (384 job URLs) + sitemap3.xml (86 job URLs), ~66 physician-slug matches pre-filter. Verified 2026-06-13: /job/JR-53304/Physician-Primary-Care-Lake-Oconee-Greene-County returns @type:JobPosting, employer='5000 Wellstar Medical Group, LLC', occupationalCategory=Providers, full HTML description (pipeline UA confirmed). employer field set to 'Wellstar Medical Group' so normEmployer → 'wellstar medical' = DOL PI normKey directly. GA-based regional health system (Kennestone, Cobb, MCG Health).",
  },
  {
    id: "jsonld-miami",
    tier: 1,
    connector: "jsonld",
    label: "University of Miami / UHealth — physicians (Phenom)",
    handle: "https://careers.miami.edu/us/en/search-results?keywords=physician",
    employer: "University of Miami",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 36 certified positions). ATS = Phenom (tenant UOMUOMUS), hosted at careers.miami.edu. careers.miami.edu/sitemap.xml → sitemapindex with 4 sub-sitemaps (sitemap1-4.xml, 526+500+500+487 total job URLs = 2013 total, ~380 physician-slug pre-filter across 4 sitemaps). Verified 2026-06-13: /us/en/job/R100091492/UMMG-Staff-Physician-Diagnostic-Radiology-Nuclear-Medicine returns @type:JobPosting, hiringOrganization.name='UOMUOMUS', occupationalCategory='Faculty & Physicians', location=Miami FL. EMPLOYER_ALIAS 'uomuomus'→'university of miami' required (Phenom org code, not a readable name). Backend ATS is Workday (umiami tenant, per job description 'log in to Workday'). UMMG = University of Miami Medical Group. FL-based academic medical center (Jackson Memorial Hospital, UHealth Tower, Bascom Palmer Eye).",
  },
  {
    id: "jsonld-uabmedicine",
    tier: 1,
    connector: "jsonld",
    label: "UAB Medicine — physicians (iCIMS)",
    handle: "https://uabmedicine.icims.com/jobs/search?ss=1&searchKeyword=physician",
    employer: "University of Alabama Birmingham Medicine",
    enabled: false,
    needsVerification: true,
    note: "DISABLED 2026-06-12: The Step 2 probe subdomain 'careers-uabmedicine.icims.com' is a CDN proxy for the UAB Medicine hospital website (WordPress), not the iCIMS job portal. Alternative portal 'uabmedicine.icims.com' timed out (connection refused). DOL iron-core (7/7 years, 93 FY2025 positions). Revisit if correct iCIMS portal URL found.",
  },
  {
    id: "workday-kumc",
    tier: 1,
    connector: "workday",
    label: "University of Kansas Medical Center — physicians (Workday)",
    handle: "kumc/wd5/kumc-jobs",
    employer: "University of Kansas Medical Center",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 18 certified positions). Workday site confirmed 2026-06-12: kumc.wd5.myworkdayjobs.com/kumc-jobs, CXS HTTP 200, ~23 'physician' hits. jobFamilyGroup has no 'Physician' descriptor so keyword fallback is used (acceptable at this volume). Academic medical center, KS.",
  },
  {
    id: "workday-geisinger",
    tier: 1,
    connector: "workday",
    label: "Geisinger Clinic — physicians (Workday)",
    handle: "geisinger/wd5/GeisingerExternal",
    employer: "Geisinger Clinic",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 78 certified positions FY2025). Workday site confirmed 2026-06-12: geisinger.wd5.myworkdayjobs.com/GeisingerExternal, CXS HTTP 200. No jobFamilyGroup facets exposed (0 values) → keyword 'physician' fallback (~888 results, scanned up to 500). 6-10 physician-titled jobs confirmed in sample. PA academic health system; specialties span all major physician SOCs.",
  },
  {
    id: "workday-roswellpark",
    tier: 1,
    connector: "workday",
    label: "Roswell Park Cancer Institute — physicians (Workday)",
    handle: "roswellpark/wd5/ExternalCareers",
    employer: "Roswell Park Cancer Institute",
    enabled: true,
    needsVerification: true,
    note: "Handle confirmed 2026-06-13 from roswellpark.org/careers page source (href to roswellpark.wd5.myworkdayjobs.com/ExternalCareers). DOL iron-core: 'roswell park cancer institute' 7yr/45pos FY2025. NY state cancer center (Buffalo). Re-enabled 2026-06-13 after wd5 CDN recovery.",
  },
  {
    id: "workday-urmc",
    tier: 1,
    connector: "workday",
    label: "University of Rochester Medical Center — physicians (Workday)",
    handle: "rochester/wd5/UR_Staff",
    employer: "University of Rochester",
    enabled: true,
    needsVerification: true,
    note: "Handle confirmed 2026-06-13 from urmc.rochester.edu careers page source (redirect to rochester.wd5.myworkdayjobs.com/UR_Staff/job). DOL iron-core: 'university of rochester' 6yr/35pos FY2025. UR_Staff covers all UR jobs including URMC clinical/academic. May also cover Unity Hospital of Rochester (7yr/24pos). Re-enabled 2026-06-13 after wd5 CDN recovery.",
  },
  {
    id: "workday-rochestergeneral",
    tier: 1,
    connector: "workday",
    label: "Rochester General Hospital (RRHS) — physicians (Workday)",
    handle: "rrhs/wd5/RRH",
    employer: "Rochester General Hospital",
    enabled: true,
    needsVerification: true,
    note: "Handle confirmed from careers.rochesterregional.org redirect to rrhs.wd5.myworkdayjobs.com/RRH. DOL iron-core sponsor (7/7 years FY2019-FY2025, 110 recentYearPositions FY2025). normKey 'rochester general hospital' direct persistence_index match. Rochester Regional Health System (RRHS) is the parent. Re-enabled 2026-06-13 after wd5 CDN recovery.",
  },
  {
    id: "workday-bostonmedical",
    tier: 1,
    connector: "workday",
    label: "Boston Medical Center — physicians (Workday)",
    handle: "bmc/wd1/BMC",
    employer: "Boston Medical Center Corporation",
    enabled: true,
    needsVerification: true,
    note: "Handle confirmed 2026-06-13 from careers.bmc.org/jobs/search page source (bmc.wd1.myworkdayjobs.com/en-US/BMC). DOL iron-core: 'boston medical center corporation' 7yr/24pos FY2025. Safety-net academic medical center, Boston MA. normKey 'boston medical center' direct match. Re-enabled 2026-06-13 after wd1 CDN recovery.",
  },
  {
    id: "workday-ahn",
    tier: 1,
    connector: "workday",
    label: "Allegheny Health Network (AHN) — physicians (Workday)",
    handle: "highmarkhealth/wd1/highmark",
    employer: "Allegheny Health Network",
    enabled: true,
    needsVerification: true,
    note: "Handle confirmed 2026-06-13 from ahn.org/careers redirect to careers.highmarkhealth.org; Workday job URLs embed highmarkhealth.wd1.myworkdayjobs.com/highmark/job/... AHN is part of Highmark Health. DOL iron-core: 'allegheny clinic' 7yr/31pos FY2025. EMPLOYER_ALIAS 'allegheny health network' → 'allegheny clinic' already in sponsor-universe.ts. Re-enabled 2026-06-13 after wd1 CDN recovery.",
  },
  {
    id: "workday-mcw",
    tier: 1,
    connector: "workday",
    label: "Medical College of Wisconsin — physicians (Workday)",
    handle: "mcw/wd503/ExternalCareers",
    employer: "Medical College of Wisconsin",
    enabled: true,
    needsVerification: true,
    note: "Medical College of Wisconsin — academic AMC in Milwaukee, WI (Froedtert & MCW Health Network). DOL iron-core: 'medical college of wisconsin' 6yr/39pos FY2025 (normKey direct match); also 'medical college of wisconsin affiliated hospitals' 7yr/21pos (separate entity; same Workday portal covers both). CXS endpoint confirmed 2026-06-13: mcw.wd503.myworkdayjobs.com/ExternalCareers, HTTP 200, 248 physician-keyword hits. wd503 is a functional Workday datacenter (not wd1/wd5). jobFamilyGroup facets: Faculty (165) — selected by physicianFacetIds() via d.includes('faculty'); Clinical Services (66) — not selected (contains Staff Physician but also NP/PA). Many Faculty titles include Froedtert hospital affiliation (e.g. 'Gastroenterologist - Staff Physician - Froedtert Moorland Reserve Health Center'). NONPHYS concern: 'Physician & APP Recruiter' → caught by existing 'recruiter' NONPHYS_TOKEN. 'Physician & APP Recruitment Sourcing Specialist' → 'recruiter' is NOT a substring of 'recruitment'; may need 'recruitment sourcing' or 'sourcing specialist' token if it appears in Faculty family.",
  },
  {
    id: "workday-adventhealth",
    tier: 1,
    connector: "workday",
    label: "AdventHealth — physicians (Workday)",
    handle: "adventhealth/wd12/AH_External_Career_Site",
    employer: "AdventHealth",
    enabled: true,
    needsVerification: true,
    note: "Rebranded from Adventist Health System in 2019. DOL iron-core: adventist health system sunbelt (6yr active, 107 recentYearPositions FY2025). EMPLOYER_ALIAS adventhealth→adventist health system sunbelt. CXS endpoint confirmed 2026-06-12: adventhealth.wd12.myworkdayjobs.com, site=AH_External_Career_Site, HTTP 200, 2000 'physician' keyword hits. Physician density ~13% in top-results sample: OBGYN Physician, AHMG Hematology Oncology Physician, OB Hospitalist Physician, Lead Hospitalist, Primary Care Physician confirmed in first 40 results. Multi-state system headquartered FL (also CO, TX, GA, KS, KY, etc.). NONPHYS_TOKENS hardened 2026-06-12 for APP-prefix APP, physician-relations, physician-coder, physician-informatics patterns observed in AdventHealth ATS.",
  },
  {
    id: "workday-mgb",
    tier: 1,
    connector: "workday",
    label: "Mass General Brigham — physicians (Workday)",
    handle: "massgeneralbrigham/wd1/MGBExternal",
    employer: "Mass General Brigham",
    enabled: true,
    needsVerification: true,
    note: "Mass General Brigham (formerly Partners Healthcare; includes MGH, Brigham & Women's, etc.). DOL iron-core: mass general brigham (6yr active, 73 recentYearPositions FY2025). normEmployer('Mass General Brigham') → 'mass general brigham' — direct DOL match, no alias needed. CXS endpoint confirmed 2026-06-13: massgeneralbrigham.wd1.myworkdayjobs.com/MGBExternal, HTTP 200, 1036 'physician' keyword hits. Physician density ~55% in first 20 (11 physician attending + 9 PA/other). PHYS_TOKENS: 'physican' (MGB ATS typo of 'physician') added to engine.ts to catch 'Physican Urology', 'Physican-Pediatrics' etc. No employer-specific false positives identified in sample scan.",
  },
  {
    id: "workday-musc",
    tier: 1,
    connector: "workday",
    label: "MUSC — physicians (Workday)",
    handle: "musc/wd1/MUSC",
    employer: "Medical University of South Carolina and Affiliates",
    enabled: true,
    needsVerification: true,
    note: "MUSC (Medical University of South Carolina and Affiliates). DOL iron-core: 7yr active, 49 recentYearPositions FY2025. Exact DOL legal name used as employer → normEmployer('Medical University of South Carolina and Affiliates') = 'medical university of south carolina and affiliates' = direct DOL normKey (no alias needed). A separate 1yr/0pos entry with normKey 'medical university of south carolina' (SPONSOR_DATA) would have blocked an alias. CXS endpoint confirmed 2026-06-13: musc.wd1.myworkdayjobs.com/MUSC, HTTP 200, 932 'physician' keyword hits. Physician density ~25% (5/20 in first page: Neurosurgery Physician, Urology Physician, Anesthesia Physician, ENT Physician, UNIV Open Rank Physician). Remaining 75% are NP/PA ('Nurse Practitioner or Physician Assistant') blocked by existing NONPHYS_TOKENS. No sponsorship denial fields in CXS or job detail HTML. Job detail HTML: employer org 'C018 MUSC Community Physicians (MCP)' in structured data — use source.employer from registry for normEmployer lookup.",
  },
  {
    id: "workday-brownhealth",
    tier: 1,
    connector: "workday",
    label: "Brown Health (Lifespan) — physicians (Workday)",
    handle: "brownhealth/wd12/External_Careers",
    employer: "Brown Health",
    enabled: true,
    needsVerification: true,
    note: "Brown Health (formerly Lifespan Health System, rebranded ~2023). DOL iron-core: 'lifespan physician' (7yr active, 48 recentYearPositions FY2025). EMPLOYER_ALIAS in sponsor-universe.ts: 'brown health' → 'lifespan physician'. 'brown health' is not in persistence_index as a standalone key, so no normKey collision. CXS endpoint confirmed 2026-06-13: brownhealth.wd12.myworkdayjobs.com/External_Careers, HTTP 200, 770 'physician' keyword hits. Physician density ~79% in 100-sample (real: Physician, MG Physician, Physician PD, Hospitalist, Pediatrician, Staff Physician, Physician Gen Cardiology, Physician - Primary Care, Staff Physician Emergency Medicine; blocked by NONPHYS_TOKENS: NP/PA, 'Sr. Physician Liaison' → new 'physician liaison' token added engine.ts run 0303).",
  },
  {
    id: "jibe-emory",
    tier: 1,
    connector: "jibe",
    label: "Emory University — physician faculty (Jibe/iCIMS)",
    handle: "https://careers.emory.edu",
    employer: "Emory University",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 40 certified positions). ATS = Jibe (iCIMS wrapper). Physician faculty jobs at faculty-emory.icims.com — individual job pages are SPA-rendered (no JSON-LD), but careers.emory.edu/api/jobs returns full JSON with title, HTML description, city/state, apply_url. Verified 2026-06-12: API returns 200, totalCount ~1860 for keyword=physician. Jibe connector fetches pages, filters by isPhysician(), collects up to 40 physician-titled jobs. GA academic system, high J-1/H-1B density.",
  },
  {
    id: "jibe-maimonides",
    tier: 1,
    connector: "jibe",
    label: "Maimonides Medical Center — physicians (Jibe)",
    handle: "https://careers.maimo.org",
    employer: "Maimonides Medical Center",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 191 recentYearPositions FY2025). normKey 'maimonides medical center' matches persistence_index directly — no alias needed. ATS = Jibe (cid:'maimo'). careers.maimo.org is the dedicated Jibe instance (jasession cookie, JSON content-type confirmed 2026-06-13); careers.maimo.org/api/jobs?keyword=physician returns HTTP 200, totalCount=200. Physician density ~6% after isPhysician() filtering. Brooklyn NY; specialties cover internal medicine, hospitalist, psychiatry, pediatric subspecialties.",
  },
  {
    id: "jibe-ynhhs",
    tier: 1,
    connector: "jibe",
    label: "Yale New Haven Health System — physicians (Jibe/iCIMS)",
    handle: "https://jobs.ynhhs.org",
    employer: "Yale-New Haven Hospital",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 62 recentYearPositions FY2025). source.employer='Yale-New Haven Hospital' → normKey 'yale new haven hospital' = direct persistence_index match. ATS = Jibe (iCIMS wrapper) at jobs.ynhhs.org (HTTP 200 confirmed 2026-06-13; careers.ynhh.org has self-signed SSL — use jobs.ynhhs.org instead). external-ynhhs.icims.com/jobs has loginOnly=1 but jobs.ynhhs.org/api/jobs is public JSON API. Low physician density (~3/1516 keyword results = OBGYN Physician, OB/GYN Per Diem, Hospice Physician); Jibe pagination returns same 3 jobs at all offsets (pinned top results). Expect 3 SPONSOR_LEAD per run — Yale YSM academic faculty recruited separately. CT-based (New Haven, Bridgeport, Greenwich hospitals).",
  },
  {
    id: "jibe-osf",
    tier: 1,
    connector: "jibe",
    label: "OSF HealthCare — physicians (Jibe/iCIMS, Physicians tag)",
    handle: "https://www.osfcareers.org",
    employer: "OSF Multi-Specialty Group",
    enabled: true,
    needsVerification: true,
    jibeQuery: "keyword=&tags=Physicians",
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 69 recentYearPositions FY2025). source.employer='OSF Multi-Specialty Group' → normKey 'osf multi-specialty group' = direct persistence_index match (7yr/69pos). Also covers normKey 'osf healthcare system' (6yr/29pos). ATS = Jibe (iCIMS wrapper) at osfcareers.org (ng-app=jibeapply confirmed 2026-06-13). Default keyword=physician returns all-staff pinned results (no physician titles); tags=Physicians filter required — osfcareers.org exposes a Physicians category that returns genuine attending titles (Neurohospitalist, Psychiatry Physician, Vascular Surgeon, Cardiologist, Oncologist, etc.). totalCount=194 physician-tagged jobs; pagination pins at offset=100 (Jibe limit) → 100 accessible per run. IL-based system (Peoria, Rockford, Bloomington, Ottawa, Galesburg service areas). 'Physician Informatics Specialist' correctly rejected by 'physician informatics' NONPHYS token. applyphysicians-osfhealthcare.icims.com is the iCIMS backend but the Jibe public API is used here.",
  },
  {
    id: "findly-upmc",
    tier: 1,
    connector: "findly",
    label: "UPMC — physicians (Findly/Google CTS)",
    handle: "companies/4c0b87d3-a9b3-4243-b9c7-2ad12c533ab3",
    employer: "University of Pittsburgh Physicians",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 89 recentYearPositions FY2025). ATS = Findly CWS backed by Google Cloud Talent Solution; public JSONP endpoint at jobsapi-google.m-cloud.io/api/job/search (no auth). Company ID confirmed 2026-06-13 from upmc.site.findly.com cws_opts.org_id. Filter: customAttributeFilter='primary_category=\"Physicians\"' narrows server-side to Physicians category (~7 jobs). Underlying ATS is Taleo (upmcjobs.taleo.net) — Findly surfaces only jobs explicitly categorized as Physicians; may underrepresent actual UPMC physician openings. normKey 'university of pittsburgh physicians' matches persistence_index directly — no alias needed.",
  },
  {
    id: "atom-uky",
    tier: 1,
    connector: "atom",
    label: "University of Kentucky Healthcare — physicians (PeopleAdmin Atom)",
    handle: "https://ukjobs.uky.edu/postings/all_jobs.atom",
    employer: "University of Kentucky",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 48 recentYearPositions FY2025). normKey 'university of kentucky' matches persistence_index directly — no alias needed. ATS = PeopleAdmin at ukjobs.uky.edu; all_jobs.atom feed confirmed 2026-06-13 (805 total entries, ~146 physician-titled). Feed includes full HTML job descriptions in <content> element. Two explicit J-1 physician jobs confirmed in feed (Pediatric Radiologist, Vascular & Interventional Radiologist). Remaining physician postings will be promoted via sponsorEnrich(). ukjobs.uky.edu handles all UK positions including UK Healthcare (hospital and academic).",
  },
  {
    id: "workday-lvhn",
    tier: 1,
    connector: "workday",
    label: "Lehigh Valley Health Network — physicians (Workday)",
    handle: "lvhn/wd1/LVHN",
    employer: "Lehigh Valley Hospital",
    enabled: true,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 33 recentYearPositions FY2025). ATS = Workday at lvhn.wd1.myworkdayjobs.com/LVHN (confirmed 2026-06-13, 715 physician-keyword hits). source.employer='Lehigh Valley Hospital' → normKey 'lehigh valley hospital' = direct persistence_index match (DOL legal name: Lehigh Valley Hospital INC.; 'inc' stripped by normEmployer). No jobFamilyGroup facet labels exposed (8 facets, all empty value strings) → keyword+isPhysician fallback. ~40 physician-titled jobs expected per run. PA-based network (Allentown, Stroudsburg, Hazleton service area).",
  },
  {
    id: "jibe-ufhealth",
    tier: 1,
    connector: "jibe",
    label: "UF Health — physicians (Jibe/iCIMS, BLOCKED)",
    handle: "https://jobs.ufhealth.org",
    employer: "University of Florida",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-13: UF Health Jibe portal (jobs.ufhealth.org) returns all-staff pinned results regardless of keyword. keyword=physician and keyword=attending+physician both return the same 1429 results (first titles: Strategic Sourcing Analyst, Transplant Assistant, Organ Procurement Coordinator). tags=Physicians returns 0. No physician-specific Jibe category available. DOL iron-core: 'university of florida' 6yr/90pos FY2025. Physician recruitment likely handled through UF academic HR separately. Revisit only if UF Health adds a physician-specific Jibe category.",
  },
  {
    id: "jibe-medstar",
    tier: 1,
    connector: "jibe",
    label: "MedStar Health — physicians (Jibe/iCIMS, BLOCKED)",
    handle: "https://careers.medstarhealth.org",
    employer: "MedStar Medical Group",
    enabled: false,
    needsVerification: false,
    note: "DISABLED 2026-06-13: MedStar Health Jibe portal (careers.medstarhealth.org) returns all 1067 results regardless of keyword (pinned). Same first title 'Medical Assistant' on page 0 and page 1. tags=Physicians returns 0; all keyword variants return 1067. Only 2 unique physician-titled jobs found (Emergency Medicine Physician, Inpatient Nephrology PA) across 10-page scan — both repeated 10x from pinning. DOL iron-core: 'medstar medical group' 7yr/60pos, 'medstar - georgetown medical center' 7yr/55pos. Revisit only if MedStar adds a physician-specific Jibe category.",
  },
  {
    id: "jsonld-guthrie",
    tier: 1,
    connector: "jsonld",
    label: "Guthrie Clinic — physicians (Oracle HCM)",
    handle: "https://careers.guthrie.org/search-results?keyword=physician",
    employer: "Guthrie Medical Group",
    enabled: false,
    needsVerification: true,
    note: "DOL iron-core sponsor (7/7 years FY2019-FY2025, 12 certified positions) under 'Guthrie Medical Group, P.C.'. ATS = Oracle HCM (detected via scale-sponsors.ts probe 2026-06-12). fetchJsonLd SPA fallback will attempt sitemap enumeration for /job/ URLs. DISABLED pending manual verification that sitemap at careers.guthrie.org includes physician job URLs with JSON-LD. PA/NY regional health system.",
  },
  {
    id: "jibe-novanthealth",
    tier: 1,
    connector: "jibe",
    label: "Novant Health — physicians (Jibe)",
    handle: "https://novanthealth.jibeapply.com",
    employer: "Novant Health",
    enabled: true,
    needsVerification: true,
    jibeQuery: "keyword=&categories=Physicians",
    note: "Novant Health (NC/SC/VA system, 40+ hospitals). Jibe ATS confirmed 2026-06-13 at novanthealth.jibeapply.com. Physician category filter: 'categories=Physicians' returns exactly 183 physician jobs (vs 1634 total for keyword=physician). NOT 'tags=Physicians' (returns 0). DOL iron-core: 'novant medical' 7yr/11pos FY2025 (NC). EMPLOYER_ALIAS 'novant health' → 'novant medical' added to sponsor-universe.ts. All 183 physician-category jobs expected SPONSOR_LEAD via sponsorEnrich(). Apply URLs via iCIMS (external-novanthealth.icims.com).",
  },
  {
    id: "workday-bannerhealth",
    tier: 1,
    connector: "workday",
    label: "Banner Health — physicians (Workday)",
    handle: "bannerhealth/wd108/Careers",
    employer: "Banner Health",
    enabled: true,
    needsVerification: true,
    note: "Confirmed wd108 tenant 2026-06-13 via www.bannerhealth.com/careers link to bannerhealth.wd108.myworkdayjobs.com/Careers (HTTP 200). DOL iron-core: 'banner medical' 7yr/44pos FY2025 (AZ); 'banner university medical' 7yr/60pos (AZ, GME/academic). EMPLOYER_ALIAS 'banner health' → 'banner medical' added to sponsor-universe.ts. CXS probe: only 3 jobs in 'Physicians' job family (below 5-threshold) so pipeline uses keyword-search fallback. Expect low yield on a given day but will capture openings as they post. Large AZ/CO/WY/NV/NE health system.",
  },
  {
    id: "avature-rss-aah",
    tier: 1,
    connector: "avature-rss",
    label: "Advocate Aurora Health — physicians (Avature RSS)",
    handle: "https://clinicianjobs.advocatehealth.org/careers/SearchJobs/feed/?jobRecordsPerPage=200",
    employer: "Advocate Aurora Health",
    enabled: true,
    needsVerification: true,
    note: "Advocate Aurora Health (merged 2022, IL+WI) physician recruiting portal at clinicianjobs.advocatehealth.org powered by Avature (advocateaurorahealth.avature.net). Job detail pages are JS-rendered; only RSS feed is bot-accessible. Feed URL confirmed 2026-06-13: HTTP 200, 20 physician jobs (Internal Medicine, Family Medicine, Neurology, GYN-ONC, Psychiatry, Anesthesiologist, REI, MFM, Rheumatology, OB/GYN, Emergency Medicine, Pediatric Radiology). URL slug used for isPhysician() check and display title; internal RSS title in rawText. DOL iron-core: 'aurora medical' 7yr/33pos FY2025 (WI legacy entity). EMPLOYER_ALIAS 'advocate aurora health' → 'aurora medical' added to sponsor-universe.ts. All 20 jobs expected SPONSOR_LEAD via sponsorEnrich().",
  },
  {
    id: "tier3-practicelink",
    tier: 3,
    connector: "none",
    label: "PracticeLink",
    handle: "",
    enabled: false,
    needsVerification: false,
    note: "Never crawl. Discovery reference only; verify on employer site.",
  },
  {
    id: "tier3-practicematch",
    tier: 3,
    connector: "none",
    label: "PracticeMatch",
    handle: "",
    enabled: false,
    needsVerification: false,
    note: "Never crawl.",
  },
  {
    id: "tier3-doccafe",
    tier: 3,
    connector: "none",
    label: "DocCafe",
    handle: "",
    enabled: false,
    needsVerification: false,
    note: "Never used.",
  },
];

export function enabledSources(): SourceDef[] {
  return SOURCES.filter((s) => s.enabled && s.connector !== "none");
}
